<meta charset="UTF-8"/>
<style>div#main{margin-top: -115px}</style>
<div id="pagesfd">
    <h2>Paradox Love</h2>
    <h4>Capítulo 3 – Nova rota e uma situação inesperada.</h4>
<h5>
    No meu caminho alternativo passei por um parque aonde crianças brincavam de bola, então parei um pouco e comecei a assistir a diversão dos jovens. Enquanto assistia um deles chutou a bola e ela veio parar nos meus pés e uma das crianças veio me pedir.<br/>
    - Onii-san<sup>6</sup> poderia jogar a bola, por favor. <br/>- Claro. (pegando a bola e entregando) Mas com uma condição (recolhendo a bola novamente). <br/>- Qual?<br/> - Posso jogar com vocês?<br/> - Mas você é mais velho e mais forte isso é injusto! <br/>- Eu não vou pegar pesado com vocês e sim me divertir.  <br/>- Tudo bem então Onii-san vamos!<br/>
    Jogar bola com aquelas crianças me ajudou a relaxar. Era o que eu precisava naquele momento tanto que nem vi o tempo passar. Já cansado sentei ao chão junto o garoto com quem tinha conversado mais cedo.<br/>
    - Qual seu nome garoto? – Perguntei <br/> - Me chamo Tachibana Maruo.<br/> - Maruo-kun, interessante... Espera qual seu sobrenome mesmo? (surpreso com a coincidência) <br/>- Tachibana.<br/> - Você é irmão da – (Interrompido) <br/>- Maruo-kun a mamãe está chamando! (Inaho chega ao parque aonde brincávamos). O que faz aqui Takeyama-kun? (surpresa)<br/>
    - Como assim? Eu estou jogando bola com as crianças. E o que você está fazendo aqui? <br/>- Eu vim buscar meu irmão para o jantar. Você já viu a hora? São mais de cinco da tarde!<br/> - Nem vi o tempo passar enquanto estava aqui. Estava precisando mesmo relaxar. <br/>- Entendo, afinal é com crianças que você está lidando. <br/>- Eu não vou levar isso como uma ofensa.<br/>
    Maruo-kun entra na conversa.<br/>
    - Quem é você Onii-san? De onde conhece a Nee-san <br/>- Que rude falar assim com seu Onii-san. Eu sou colega de classe de sua irmã, eu me chamo Takeyama Kaito. - Aaaaaaaaah (fica agitado) foi você quem salvou minha Nee-san! Foi ele quem te salvou Nee-san! Você é tão legal Onii-san, quero ser como você quando crescer! <br/>- Sim Maruo, foi ele, mas não pense que ele é um cara legal. Mas vamos deixar isso de lado e vamos pra casa.<br/> - Sim Nee-san. Tchauonii-san! <br/>- Tchau Tachibana-kun!<br/>
    *ambos acenam se despedindo*<br/>
</h5><fieldset><a id="asteristico">
            6 Nota ao leitor (não reclame, por que eu tenho que explicar pra você entender): Onii-san (ou One-san, ou Nee-san, usado para mulheres) é uma forma dos mais jovens se referirem a jovens mais velhos que eles de forma respeitosa, é como se dissessem “Irmãozão” ou “Irmanzona”.</a>
    </fieldset>
    <div id="pagenum">Capítulo 3 – Nova rota e uma situação inesperada. | 11 |</div> </div><div id="pages"><h5>
    Depois de vê-los ir embora deitei na grama do parque e fechei os olhos por alguns minutos descansando, e pouco tempo depois uma voz familiar me chama.<br/>
    - Takeyama-kun! Ei Takeyama-kun!<br/>
    Quando abro os olhos vejo uma moça de cabeça pra baixo me olhando. É a Inaho. O que ela queria comigo naquele momento? Brigar por ter falado com o irmão dela?<br/>
    - Oi! O que quer de mim agora? - Calma eu não vim aqui brigar. Estou aqui contra a minha vontade. - O que aconteceu? - Quando chegamos em casa o Maruo contou pra minha mãe que tinha brincado com o rapaz que tinha me salvado. Minha mãe acabou ficando toda animada por que ela queria conhecer esse rapaz. - E então?<br/>

    - Sábado na minha casa a noite. (fala de forma não muito conforTável, não me olhando nos olhos)<br/> - Como assim? (muito surpreso) <br/>- Ela vai preparar um jantar pra você. Eu falei que não precisava, mas ela não me deu ouvidos. <br/>- Éééé... (ainda surpreso)... Como eu reajo a isso? <br/>- Só vá, caso contrário ela vai se sentir muito ofendida. E é provável que ela não me deixe marcar nada com minhas amigas no sábado por isso. <br/>- Então eu não tenho escapatória? <br/>- Não. Só vá e conte como tudo aconteceu, coma e vá embora.<br/> - Então tudo bem, talvez eu chegue a tempo. <br/>- Tudo bem. Boa noite <br/>- Boa noite.<br/>
    Uma situação totalmente inesperada, um jantar na casa da garota que gosto, mas que me odeia. Nunca imaginaria que isso pudesse acontecer e muito menos comigo. Levantei-me da grama e fui para casa.  Depois de ter tomado banho e jantado fui para meu quarto estudar e adiantar minhas atividades. Já na cama comecei a pensar no meu dia e em tudo o que aconteceu. Como depois de levar um tapaeu iria jantar na casa da Inaho? Tudo estava muito confuso na minha mente, aparecer na casa dela assim do nada, que esquisito. Aaargh! Não posso ficar pensando demais nisso se não posso estragar tudo. Pela manhã tomei o mesmo caminho da volta de ontem e percebi alguns pontos da minha vizinhança que eu não conhecia como, por exemplo, uma Sakura(Árvore cerejeira) toda florida por causa da primavera, uma padaria e uma loja de CDs. No portão de entrada da escola, Natsu-sensei me esperava com alguns papéis em mãos. Se não me engano ele estava à espera do nosso plano de ação para os jogos das próximas semanas.<br/>
    - Bom dia sensei! <br/>- OowTakeyama, bom dia! Estava esperando você chegar. Temos que juntar o time no intervalo para dar início aos treinos e a preparação física de todos vocês.<br/> - Ok! Ontem eu analisei os últimos resultados do time tracei algumas metas, e percebi que vamos ter que mudar o treino de resistência dos zagueiros e o treino de explosão dos atacantes. <br/>- Compreendo. No intervalo vamos discutir mais sobre isso, mas agora vá pra sala que as aulas já estão por começar. <br/>- Vou avisar o pessoal sobre a reunião de hoje, até mais!<br/> - Faça isso.<br/>

    No corredor das salas me encontrei com o Genji e caminhamos até a sala.
    - E aí Kaito, bom dia! <br/>- Bom dia! <br/>- Está melhor? <br/>- Depois de ontem? Acho que sim. *ambos riem* </h5><div id="pagenum">Capítulo 3 – Nova rota e uma situação inesperada. | 12 |</div> </div><div id="pages"><h5> - O que fez ontem quando foi embora? <br/>- Joguei bola com algumas crianças em parque perto de casa. Mas o mais impressionante aconteceu no final. Depois do jogo conheci o irmão da Tachibana-san. <br/>- Wow! Como você descobriu isso? <br/>- Ela foi buscá-lo quando acabamos de brincar.<br/> - Hahaha querendo aumentar as relações com a família da moça? <br/>- Vou jantar na casa dela sábado. (falo de forma inesperada)<br/> - [...] O quê?! Isso é uma brincadeira, certo? <br/>- Não. A mãe dela me convidou pra jantar.<br/> - Mas você conhece a família dela? <br/>- Não.<br/> - Não entendi. Então qual foi o motivo?<br/> - Os pais dela querem conhecer o rapaz que a salvou há dois dias.<br/> - Me conta essa história direito Kaito!<br/> - Ela quase foi atropelada na segunda e eu a salvei, por isso estou com o braço enfaixado. <br/>- Wow! Você é meu herói, Kaito.
    Já na porta da sala voltamos a rir, porém foi um momento infeliz. Inaho estava perto da porta e no viu. No mesmo instante me calei, mas Genji continuou rindo. Dei uma cotovelada em seu estômago para calar sua boca, nesse momento ele percebeu a situação em que estávamos e logo se calou por falta de ar. Nós três ficamos nos encarando, em silêncio, parados em frente à porta. Eu não sabia como agir naquele momento, muito menos o Genji, mas Inaho me olhava nos olhos seriamente e com muita indiferença.<br/>
    - Bom dia garotos. (Inaho nos cumprimenta) <br/>- Bom dia.<br/> - Bom dia.<br/>


    Ela voltou ao seu lugar enquanto ficamos calados e sem reação. Olhei para Genji e ele me respondeu fazendo uma cara de “O que acabou de acontecer aqui?” e eu respondi encolhendo os ombros e levantando as mãos como que dizendo “Sei lá”.  Nosso professor estava parado em frente à porta nos observando.<br/>
    - Vão ficar quanto tempo parados aí? Vocês vão me deixar entrar? - Oh! Nakamura sensei, perdão! (respondi enquanto ambos nos curvávamos em respeito)
    Depois de termos comido, Genji e eu fomos para a sala do clube para a reunião sobre as partidas preparatórias. Natsu-sensei deu algumas instruções sobre as partidas e os treinamentos. Enquanto falava ele parou e me chamou para falar sobre o treinamento da equipe. Fui para frente da sala e comecei a dar as coordenadas:</h5><div id="pagenum">Capítulo 3 – Nova rota e uma situação inesperada. | 13 |</div> </div><div id="pages"><h5>
    - (falando de forma autoriTária) Pessoal os dois times que iremos enfrentar são bons, tanto que os resultados mostram isso muito bem. A Seiho ganhou no ano retrasado e perdeu para nós na final da copa de Inverno e a Mahou Tai sempre disputa as quartas de final, porém elas têm aumentado seu rendimento em forma de gols e substituições. Nós ainda não a enfrentamos e essa é a nossa desvantagem. Mas nós não iremos trabalhar em cima das fraquezas dos adversários e sim nas nossas.  Nos últimos jogos percebi algumas aberturas na defesa que podem ser um problema contra times mais fortes, e se não dermos um jeito nisso, nosso primeiro Campeonato Nacional será um fiasco. Vamos ajustar nossas jogadas de bola parada e também o avanço dos laterais. Certo Kurotatsu e Maburo? (laterais titulares)  - Pode deixar capitão! - Entendido! - Muito bem pessoal, agora vamos falar do ponto chato, mas necessário: A dieta e a formulação e horário dos treinamentos. Já distribuí as dietas e espero que as sigam, pois os resultados serão imediatos, mas dessa vez eu fui bonzinho e não fui tão rígido quanto da outra vez. É para o bom rendimento de vocês pessoal. Por favor, sigam a dieta. - Como assim menos de 1 quilo de comida? Eu não vou sobreviver comendo menos disso no almoço. - E meu arroz de cada dia? - Gordura zero?
    Justamente o pessoal começou a reclamar a respeito das dietas, só fechei a cara e cerrei as sobrancelhas pros jogadores. Instantaneamente eles murcharam e se calaram. “A
    dieta é essa e pronto, nos vemos à tarde”, respondi e finalizei as instruções. O sinal tocou e voltamos à sala. No final das aulas da tarde fomos para a sala nos trocar para iniciar os treinos. Já em campo fizemos tudo o que estava em nosso cronograma, mas percebi que alguns jogadores estavam mais cansados do que de costume, então comuniquei isso ao treinador.<br/>
    - Natsu-sensei, o pessoal não parece meio desgastado? <br/>- Realmente alguns estão muito cansados, será o novo treinamento?<br/> - Não! De forma alguma. Esse treino foi só um aquecimento para os outros, acho que precisamos de suporte. <br/>- Como assim Takeyama-kun? <br/>- Precisamos de suplementos e bebidas energéticas. Como o orçamento do time está? <br/>- Talvez dê, vou verificar. Essas exigências já eram de se esperar vindo de você. Amanhã conversamos sobre isso, vamos embora! <br/>- Até amanhã sensei.<br/>
    Na volta pra casa conversava com Genji, mas meus pensamentos estavam em outro lugar. Queria dar um fim àquela discussão com a Inaho, mas não sabia como fazer. Meu amigo percebeu o quanto eu estava desatento e resolveu se aproveitar. Enquanto andava ele deu um leve toque com seu pé no meu calcanhar me fazendo tropeçar.<br/>
    - Ei o que é isso? <br/>- Você mereceu por não dar atenção ao que os outros falam. <br/>- E se eu tivesse me machucado? <br/>- Vaso ruim não quebra, imagina você!
    Fiquei irritado, mas não podia tirar a razão dele. Eu tinha criado um sentimento forte pela Inaho e queria que ela entendesse isso, mas a situação não era favorável para mim.  <br/>- Posso te fazer uma pergunta Genji? <br/>- O que foiTaka<sup>7</sup>? <br/>- Como eu resolvo esse problema? <br/>- Eu não sei cara, eu não sei, mas talvez abrir o jogo com ela possa ser de ajuda. Você não vai jantar na casa dela sábado? <br/>- Vou sim. <br/>- Aproveite esse momento para tentar explicar tudo. <br/>- Pode ser uma boa ideia, mas como faço?<br/>
   </h5><fieldset><a id="asteristico"> 7 Mais uma linda nota para você meu caro leitor: Esse é o apelido do Kaito. “Ta” de Takeyama e “Ka” de Kaito. “Taka” em japonês significa Falcão.</a> </fieldset>
    <div id="pagenum">Capítulo 3 – Nova rota e uma situação inesperada. | 14 |</div> </div><div id="pages"><h5>
    - Você também quer que eu pense em tudo! <br/>- Desculpe. <br/>- Amanhã no intervalo do almoço, use esse tempo para explicar tudo. <br/>- Pronto! É isso que vou fazer. Muito obrigado! (estende a mão) <br/>- Amanhã meu almoço é por sua conta.  <br/>- O quê?! (continua com a mão estendida e com cara de “filho da mãe”) <br/>- É justo. <br/>- Está. <br/>- Vou por aqui, até amanhã.<br/> - Tchau.<br/>
    No final da noite já na minha cama eu pensava nas palavras que usaria para falar com Inaho, mas percebi que quanto mais pensava mais ficava confuso. Nesse caso decidi que as melhores palavras seriam as que viessem na minha mente amanhã. Apaguei as luzes e tentei dormir, porém eu não conseguia, rolava de um lado para o outro da cama, me agitava e ficava cada vez mais nervoso.  Quando finalmente consegui dormir tive um sonho, ou melhor, um pesadelo. As únicas palavras que saiam da minha boca enquanto falava com Inaho eram “banana” e “paçoca”. Acordei trinta minutos mais cedo, mas eu estava horrível, por que não tinha conseguido dormir. Arrumei-me, tomei café, me despedi da minha família e saí. Enquanto lia o jornal meu pai percebeu o estado em que estava e disse para minha mãe e meu irmão:  “Essas paixões da adolescência”.</h5><div id="pagenum">Capítulo 3 – Nova rota e uma situação inesperada. | 15 |</div>

</div>
<?php $back="Cap #2"; $next="Cap #4"; $backs="?cap=2"; $nexts="?cap=4"?>