<meta charset="UTF-8"/>
<style>div#main{margin-top: -115px}</style>
<div id="pagesfd">
    <h2>Paradox Love</h2>
    <h4>Capítulo 4 – Foi embaixo dessa cerejeira que te conheci.</h4>
<h5>
    No caminho para a escola vi uma silhueta conhecida parada observando a cerejeira. Ao me aproximar acordei subitamente. Inaho estava olhando a cerejeira no novo caminho que eu fazia para a escola. Ao perceber minha presença ela se espantou.<br/>
    - O que faz aqui? E que cara é essa? E desde quando você passa por aqui? <br/>- O quê? Eu estou indo para a escola por esse caminho agora e também acordei mais cedo hoje.<br/> - Por quê? Não sabe mais quem enganar com suas mentiras?<br/> - Está muito cedo pra discutir. E foi você a culpada por eu estar assim.<br/>

    Ela ficou surpresa com o que disse e eu também, por que eu não sei como disse algo assim de forma tão natural. Provavelmente por causa do sono. Ela logo replicou o que eu tinha dito:<br/>
    - Como assim eu sou a culpada? <br/>- Eu passei a noite toda pensando no que dizer pra você na tentativa de explicar o que aconteceu.<br/> - É só isso? <br/>- Como assim só isso? <br/>- Ontem o Sakamoto-kun me procurou e explicou tudo. No começo eu não estava acreditando, mas depois do que ele disse e fez eu resolvi acreditar. <br/>- O que aconteceu?<br/>
    Nesse momento meu coração batia forte, eu não sabia o que o Genji tinha dito para Inaho, mas pelo que ela me disse a situação estava resolvida. Queria saber o que aconteceu.<br/>
    – Visão do Genji –<br/>
    Fui colega de classe da Tachibana-san no fundamental, mas ela era muito reservada quanto aos garotos. Por isso eu não sei muito sobre ela. Só posso dizer que agora ela é mais bonita do que antes. Ela não aparentava se interessar tanto por garotos em comparação com as outras garotas, ela só estudava e conversava com as garotas, nada mais. Só me lembrei dela depois do que aconteceu no final do treino de segunda-feira Depois do erro que cometi ao me meter nos assuntos amorosos do Taka me senti na obrigação de dar um fim àquele problema. Tachibana-san é uma garota legal e ambos formariam um casal ideal. Taka é organizado e equilibrado enquanto ela é desajeitada e orgulhosa. Tachibana-san atrai as pessoas ao seu redor, mas ele é um pouco anti-social.  Se eles pudessem conviver juntos e um aprender sobre o outro, daria um casal perfeito. Porém minhas expectativas foram adiadas quando ela resolveu se declarar para mim. Eu estava cansado por causa do treino, mas isso não me impedia de entender bem suas palavras. Me senti muito mal pelo meu amigo. Taka é um garoto excepcional, sem ele eu não jogaria futebol como jogo hoje, não tiraria as notas que tiro hoje (elas não são tão altas, mas são melhores do que antes). Ele nunca tinha me dito nada sobre Tachibana-san, mas o jeito como ele a olhava deixava tudo claro. E como ele nunca foi de contar para os outros sobre esse assunto sua experiência era bem limitada no quesito „não deixar perceber‟.</h5><div id="pagenum">Capítulo 4 – Foi embaixo dessa cerejeira que te conheci. | 16 |</div> </div><div id="pages"><h5>

    Quando estávamos indo pra casa ele parecia estar em outro mundo por causa de toda essa confusão. E vê-lo daquela forma me magoava, então decidi comigo mesmo que teria de fazer alguma coisa pra limpar a sujeira que fiz. Pelo que conheço dele falar com ela seria algo impossível, porém ele tem uns picos repentinos que o faz falar algo inesperado de uma hora pra outra.  Quando nos despedimos o esperei virar a esquina e fui para a casa da Tachibana, mas aí vem a pergunta: “Como eu sei aonde é a casa dela?”. No dia anterior a segui já com o objetivo de explicar tudo, mas não estava tão influenciado quanto hoje. Tudo bem que posso parecer um stalker8, mas foi por um bem maior.  Eu estava muito nervoso por bater na campainha de uma família que eu não conhecia, e o pior seria se o pai dela abrisse a porta. Mas como o universo conspira conosco ás vezes minhas expectativas foram adiadas por um senhor de uns quarenta e poucos anos. Ele me olhou de ponta a ponta, ficou com uma cara séria e a única coisa que se passava pela minha cabeça é: “Morri!”. Porém logo ele falou:<br/>
    - Pelo uniforme você deve ser da mesma escola que a Inaho. Mas você não viria sábado?<br/> - Mas hein?!<br/> - Entre e fique a vontade. (põe a mão no meu ombro)<br/>
    Eu nunca tinha ficado tão confuso quanto naquele momento, mas pelo menos eu ainda estava vivo. Eu tinha que ser rápido, mas quando menos esperava já estava sentado no sofá da sala.<br/>
    - Querida o rapaz que salvou nossa filha está aqui! <br/>- O quê? Mas o jantar não era no sábado?<br/>
    Tinha um grande mal entendido acontecendo e eu precisava intervir logo para que não virasse uma bola de neve.<br/>
    - Eu agradeço muito pelo convite, mas eu só vim falar com sua filha. <br/>- O que veio falar com ela? <br/>- *Ferrou! (mentalmente). É que... Eu só... Não é nada demais... Ela está? <br/>- Inahooo! (o pai a chama)
    Uma garota com um belo cabelo castanho amarrado e em roupas casuais desce as escadas. Agora eu entendi o porquê do Taka gostar dela. Sua feminilidade era única e
    8Notinha linda de pai: (Stalker) é o termo utilizado para perseguidor em inglês, mas aí você me pergunta: “Por que não escreve „perseguidor‟?” Por que escrever (stalker) é mais legal.<br/>


    chamativa. Enquanto descia as escadas ela mostrava um caminhar leve e solto. Mas sua reação ao me ver cortou toda a beleza do momento. Espantada ela segurou no corrimão e na parede e:<br/>
    - Aaaaah! Ei o que você está fazendo aqui Sakamoto-kun?! (se assusta enquanto desce as escadas) <br/>- Boa noite Tachibana-san! (aceno todo sem graça) -<br/> Como sabia que minha casa era aqui? <br/>- O Taka me falou?<br/> - Como assim te falou? Então se explique, por favor? O que faz na minha casa a essa hora? <br/>- Filha, não é assim que se fala com os convidados, muito mais com o rapaz que lhe salvou! (a mãe grita da cozinha) - Não foi ele </h5><div id="pagenum">Capítulo 4 – Foi embaixo dessa cerejeira que te conheci. | 17 |</div> </div><div id="pages"><h5>mãe! <br/>- Então quem é você? (o pai me olha com cara fechada).
    Acho que de hoje eu não passo, mas eu tinha que cumprir minha missão.<br/>
    - Sou colega da Tachibana-san e queria tirar algumas dúvidas com ela, serei breve, prometo! <br/>- Então vamos lá fora. (diz Inaho pegando em meu braço e me puxando pra fora)<br/>
    *No lado de fora*<br/>
    - Me diga o que quer? Seja rápido!<br/> - Preciso que acredite em mim. <br/>- Depois de tudo o que aconteceu nesses últimos dias eu não sei dizer se posso. <br/>- Então espere.<br/>
    Eu tinha que resolver aquela questão de uma vez por todas. Tinha de usar qualquer método para fazer a Tachibana-san acreditar em mim. A única ação que veio a minha mente foi me curvar para ela suplicando que acreditasse em mim. Talvez eu estivesse sendo exagerado, mas era pelo Taka. Então está decidido! Me ajoelhei e pus meu rosto no chão<sup>9</sup>.<br/>


    - Ei o que você pensa que está fazendo se curvando pra mim? E ainda por cima na porta da minha casa? (muito surpresa) <br/>- Eu preciso que você acredite em mim a todo custo. Por favor, eu imploro!<br/> - Não acha que isso é demais? <br/>- Taka faria o mesmo por mim. <br/>- Tudo bem, eu vou acreditar no que você irá dizer agora se levante. <br/>- Muito obrigado Tachibana-san, realmente muito obrigado! <br/>- Se explique rápido! <br/>- Eu fui muito tolo por ter rejeitado você e ainda mais daquele jeito! Por favor, me perdoe! <br/>- Como é? Quer voltar atrás? <br/>- Não. <br/>- O quê? Não estou entendendo mais nada! <br/>- Eu só te rejeitei por causa do meu amigo.<br/> - Takeyama-kun?<br/> - Sim, ele realmente gosta muito de você. Por isso não pude aceitar seu pedido. <br/>- Então você está se “sacrificando” pelo seu amigo? <br/>- Ele nunca gostou de garota alguma e pelo que conheço dele se ele gosta de você significa que tem algo especial em você que chama a atenção dele. <br/>- Haha sério isso? (fica um pouco corada enquanto da um riso forçado) <br/>- Então, por favor, perdoe-o! Ele não merece passar por isso. Deixe-o explicar tudo pra você. <br/>- Não sei se nossos sentimentos são os mesmos.  <br/>- Tudo bem, mas pelo menos tente entendê-lo. Ele é uma ótima pessoa. <br/>- Pare, por favor! Não continue insistindo nesse assunto. Eu já entendi e vou perdoar vocês, mas não me pressione, por favor.  <br/>- Me desculpe não era minha intenção. Fico feliz por você ter aceitado meu pedido. Agora vou embora, já fiz o que tinha de fazer. <br/> <fieldset><a id="asteristico">9 Nota de esclarecimento: Se curvar para alguém na cultura japonesa tem vários significados, de agradecimentos a súplicas o que se encaixa na ação de Genji.</a> </fieldset></h5><div id="pagenum">Capítulo 4 – Foi embaixo dessa cerejeira que te conheci. | 18 |</div> </div><div id="pages"><h5>- Boa noite Sakamoto-kun!<br/> - E agradeça aos seus pais pela hospitalidade, por favor. <br/>- Certo.<br/> - E mais uma coisa, as cerejeiras estão lindas essa primavera. Procure pela mais próxima amanhã de manhã. <br/>- Quê? Então Tá.<br/> - Tchau. <br/>- Tchau e Sakamoto-kun muito obrigada! <br/>- Por nada. (acenando de costas)<br/>


    Agora eu entendo o porquê de você gostar dela. Ela completa o que lhe falta. Espero que você consiga conquistá-la, mas se você não conseguir alguém irá fazer isso e se chegar a acontecer você pode ter certeza que irá odiar a pessoa que chegou a sua frente.
    – Voltando à conversa entre Inaho e Kaito –
    <br/>- Então foi isso o que aconteceu ontem?<br/> - Resumidamente sim. <br/>- Aquele desgraçado! (cerrando os punhos com uma feição de extremamente bravo)<br/> - Ele fez aquilo pra limpar seu nome comigo. <br/>- Eu sei, mas era eu quem tinha de fazer isso!<br/> - Seja humilde e aceite, eu te perdoo pelo que aconteceu essa semana.<br/> - Que bom, me sinto mais aliviado. Obrigado Tachibana-san. Mas me diga uma coisa.<br/> - O quê? <br/>-Você sempre passa por aqui ou hoje foi uma exceção?  <br/>- Hoje eu decidi mudar minha rota. Alguém me disse que essa cerejeira estava linda (apontado para tal).  - Realmente.<br/>
    O silêncio tomou conta da nossa conversa naquele momento. Por mais que eu já tivesse sido perdoado por ela, eu ainda estava aflito. Indiretamente ela já sabia que eu gostava dela, mas eu não sabia o que ela pensava sobre mim. Minha boca começava a ficar com um gosto amargo e meus lábios começavam a secar. Eu tinha de perguntar.<br/>
    - Tachibana-san eu preciso saber de uma coisa! (falo de forma inesperada (hoje ele está inspirado))<br/> - O que foi? (assustada) <br/>- Você já sabe que eu gosto de você, porém eu ainda não tive uma resposta. Então o que você pensa sobre mim? <br/>- Assim, a-a-agora? - Sim! Por favor! - (respirando fundo) Você não me falou eu fiquei sabendo pela boca de outra pessoa. <br/>- Isso é verdade. <br/>- Então faça direito! <br/>- Q-q-quê? <br/>- Isso mesmo, tente!<br/>

    - Éééé... Como assim? <br/>- Vamos, não temos muito tempo. Temos quinze minutos. <br/>- (puxando oxigênio e tomando coragem) Tudo bem. Preciso de coragem pra isso. <br/>- Vou me sentar aqui e escutar o que você tem a dizer. (sentando no banco perto da cerejeira) <br/>- Ok lá vai...
    Não acredito no que estava acontecendo! Eu iria me confessar para a Tachibanasan. Eu estava tão nervoso naquele momento que minhas palavras não estavam se encaixando. Eu tinha de ser simples e direto, sem escolher demais. Pronto!<br/>
    - Tachibana Inaho gostaria ser minha namorada? (muito envergonhado eu me curvo e fecho os olhos) <br/>- Muito bem Takeyama-kun, é assim que se faz (bate palmas). Agora sei que você gosta de mim. Preste atenção na minha resposta.<br/> - (mentalmente) Eu não vou aguentar essa pressão, por favor, diga sim! <br/>- Sinto muito, mas NÃO! Não posso ser sua namorada.<br/> - O QUÊ? Por quê? (O.O) <br/>- (risos) Calma Takeyama-kun, não me entenda mal por estar te rejeitando, mas na verdade eu não conheço você, por isso fiz isso. Não quero me vingar ou coisa parecida.  <br/>- Então por que está fazendo esse jogo emocional comigo? <br/>- Eu precisava saber o quanto você gosta de mim e agora eu sei.  <br/>- Você é sádica por acaso?( -_- ) <br/>- (ri ainda mais) Você é engraçado sabia? Não, não sou (tão) sádica. Digamos que eu fiz algo bom por você. </h5><div id="pagenum">Capítulo 4 – Foi embaixo dessa cerejeira que te conheci. | 19 |</div> </div><div id="pages"><h5>- O quê, como assim?<br/> - Você acabou de me mostrar um lado só seu. Preciso conhecer você antes de dizer se gosto ou não.<br/> - Mas e quanto ao Genji? Desde quando você o conhece? <br/>- Fomos colegas de classe no fundamental, porém nunca fomos próximos. Mas posso dizer que ele não mudou muito desde aquela época. <br/>- Então é isso? Ele nunca me falou de você. <br/>- Talvez não se lembre de mim. Mas é passado, o que aconteceu essa semana já me abriu os olhos. Ele mudou o suficiente. <br/>- E quanto a mim? <br/>- Quanto ao meu pedido de ontem? Vai aceitar? <br/>- Sobre sermos amigos?<br/>


    - Sim, afinal eu não posso conhecer você sem antes conversar contigo. O que acha?<br/> - Não sei, não quero entrar na Friendzone<sup>10</sup>.<br/> - Por que você acha que eu faria isso?<br/> - Meu instinto masculino me avisa pra tomar cuidado depois de hoje. Você é meio sádica. <br/>- Não sou não!<br/> - Então eu já sei o que você é!<br/> - O quê então? <br/>- Tsundere!<sup>11</sup><br/> - COMO OUSA DIZER ISSO? (se levanta) <br/>- Depois de tudo o que aconteceu eu acho que essa é a única forma de explicar. <br/>- AAAAHH!!! Ora seu... Eu vou lhe ba–  <br/>- Viu! Olha a prova aí! <br/>- Esqueça tudo o que eu disse. Você é um idiota! <br/>- Mas espera... <br/>- Não quero mais saber. É impossível sermos amigos. Tchau! (sai enfurecida) <br/>- A escola é pro outro lado! (apontando) <br/>- Eu sei! (batendo forte os pés no chão e voltando para a direção correta) <br/>- Boba! (mentalmente)
    <br/>Depois de tudo o que aconteceu nesses quinze minutos de conversa eu posso dizer que ficamos mais próximos.
    </h5>
    <fieldset><a id="asteristico">10 Nota pra você que não entendeu: Eu espero que você saiba o significado de friendzone. Caso contrário friendzone (Zona da amizade) é um estado em que a pessoa fica ao se aproximar demais de alguém que gosta com o objetivo de ficar mais íntimo, porém essa pessoa só irá lhe reconhecer como amigo. E isso é mais comum com os homens. <br/>11 Essa nota é boa: (Tsundere) é um estilo de personalidade muito difundido no mundo dos mangás e animes. Pessoas tsunderes (na maior parte das histórias mulheres) apresentam um comportamento agressivo passando para um comportamento dócil e amigável. </a> </fieldset>
   <div id="pagenum">Capítulo 4 – Foi embaixo dessa cerejeira que te conheci. | 20 |</div>


</div>
<?php $back="Cap #3"; $next="Cap #5"; $backs="?cap=3"; $nexts="?cap=5"?>