<meta charset="UTF-8"/>
<style>div#main{margin-top: -115px}</style>
<div id="pagesfd">
    <h2>Paradox Love</h2>
    <h4>Capítulo 5 – Irmão mais velho X Irmã mais velha.</h4>
<h5>
    Enquanto ela subia colina indo em direção ao colégio eu estava lá parado pensando sobre o que tinha acontecido. Me dei conta de que não podia perder aquela oportunidade. Se ela estivesse séria sobre esquecer tudo ou não, eu queria conhecê-la. “Idiota, vá atrás dela!” foi o que minha consciência gritou.  Eu posso alcançá-la antes de chegar à escola. Isso não seria nada mais que um aquecimento. Pronto estou motivado! Seremos amigos.<br/>


    Começo a correr de encontro a Inaho e a ideia de me aproximar dela me empolga cada vez mais, porém subitamente a Inércia me ataca<sup>12</sup>. <br/>Eu não sabia o que tinha me atingido, mas com certeza eu iria me zangar muito com o culpado. Levantando do chão e tirando a poeira olhei para o futuro corpo e logo me dei conta de que não poderia bater no culpado.<br/>
    - Bom dia Tachibana-kun! <br/>- Onii-san bom dia! <br/>- Por que fez isso? <br/>- Queria ver você, aí eu o encontrei aqui. Legal né?<br/> - Ôh!<br/>  - Vamos jogar bola depois da escola? <br/>- Hoje não posso, tenho treino. <br/>- Treino?<br/> - (fazendo pose de herói) Sou o capitão do time da minha escola. <br/>- Óóóh você é tão legal onii-san! <br/>- Obrigado Tachibana-kun, agora vá pra escola nos vemos depois. <br/>- Tchau onii-san! Vou passar no seu colégio pra ver você jogar. <br/>- Tudo bem. Lá nós vamos jogar um pouco. - Legal!
    Nos despedimos e seguimos em direções diferentes. Desisti de correr atrás da Inaho, mas ainda terei muito tempo pra conversar com ela. Indo para o colégio percebi que não havia muitos alunos, olhei a hora no relógio e me dei conta de que estava atrasado. Agora eu tinha de correr para pegar o portão aberto. Quando avistei o portão do colégio, ele já estava sendo fechado pelo presidente do conselho estudantil. Gritei: “Me espere!”. Mas ele não me deu ouvidos e continuou fechando o portão. Corri mais um pouco e passei no curto espaço que me sobrou.<br/>
    - Estranho ver você se atrasando Takeyama-san. <br/>- Perdão Tanabe senpai eu acabei perdendo meu horário. <br/>- Só não deixe virar costume, por favor.<br/> - Tudo bem, e muito obrigado. <br/>- Vamos voltar pra sala, o sinal está para <br/>– *Sinal toca*<br/> -Estou indo!<br/>
    <fieldset><a id="asteristico">12 Momento Física(caso você não saiba o que inércia significa): A Inércia é uma das três leis de Newton. De acordo com Newton a Inércia existe quando um objeto em movimento mantém-se em movimento até que uma força maior o impeça ou uma força aja sobre um objeto em repouso fazendo-o se movimentar. Nesse caso algo impediu o movimento do Kaito.</a> </fieldset>
</h5><div id="pagenum">Capítulo 5 – Irmão mais velho X Irmã mais velha. | 21 |</div> </div><div id="pages"><h5>

    Tanabe Kouta é o atual presidente do conselho, ele se forma esse ano. Muitos alunos gostam dele por causa do seu carisma. Ele ficou em uma boa colocação no exame nacional e está se esforçando para entrar na Universidade de Tóquio. Espero que o desejo dele se torne realidade afinal ele merece conquistar o que tanto almeja. Recebi uma leve bronca por ter chegado um pouco atrasado, mas nada que me desanimasse. Durante a aula Genji jogou um pedaço de papel com uma mensagem. Olhei para ele com cara de poucos amigos e abri o bilhete e o li:<br/>
    Conversou com ela? Dizia Genji.<br/>
    Respondi e joguei de volta.<br/>
    - Por que não me envia uma mensagem? <br/>- Assim é mais emocionante. <br/>- (-_-) - Me conte. <br/>- Você é um idiota, sabia? <br/>- Por quê?<br/> - Por que fez aquele teatro na casa dela?<br/> - Ela te contou? <br/>- Sim. <br/>- Hehe (>.<) <br/>- Sem noção!<br/> - Ontem foi emocionante, pensei que fosse morrer, mas me conte como foi! <br/>-Ela me rejeitou! ( :/ )<br/>
    Depois disso a conversa por bilhetes acabou e...:<br/>
    - ÃÃÃÃÃHM?! (grita inconscientemente pra toda a sala) <br/>- Cala boca Genji!<br/> - Aconteceu alguma coisa Sakamoto-kun? (professor se vira)<br/> - Ãhm? Eu? <br/>- Sim. Tudo bem com você? Quer ajuda? <br/>- Sim,  professor sinto muito em interromper sua aula, mas não estou me sentindo bem. <br/>- Então, por favor, Hinata-san acompanhe-o <br/>- Não professor! É algo que só outro homem iria suportar. Me acompanhe amigo! (me olha com cara de cachorro pidão) <br/>- Tudo bem se eu o acompanhar professor?


    - Esteja de volta em quinze minutos (aponta para Genji), caso contrário vocês receberão falta. <br/>- Tudo bem. </h5><div id="pagenum">Capítulo 5 – Irmão mais velho X Irmã mais velha. | 22 |</div> </div><div id="pages"><h5><br/>- Vamos Taka! (me puxa pelo braço simulando uma dor de barriga)<br/>
    Ao sair da sala Inaho me olhou de forma desconfiada já sabendo o que iria acontecer lá fora. Corremos pelos corredores até a máquina de bebida no térreo da escola. Genji estava indignado pelo que falei e queria informações sobre nossa conversa.<br/>
    - Como assim ela te rejeitou? Ela tinha perdoado você! <br/>- Eu sei, mas ela não gosta de mim. <br/>- Mas vocês pelo menos se ajeitaram? São amigos ou algo parecido? <br/>- Não! <br/>- Cara, como assim?! O que aconteceu?<br/> - Nós brigamos hoje cedo perto da sakura e por enquanto ela está brava comigo. <br/>- O que você fez? <br/>- Disse que ela era sádica!<br/> - Cara como você é burro! Pode até ser bom na escola, mas pra conversar com uma garota você é horrível! Por que você a chamou de sádica?  <br/>- A forma como ela me rejeitou. <br/>- Eu não entendo você! <br/>- Genji ela é uma tsundere. Te bate pra depois amaciar com palavras gentis. <br/>- Então foi assim? Espera você a chamou de tsundere? <br/>- Sim! <br/>- Você tem sérios problemas Taka (facepalm13). Uma tsundere não gosta de ser chamada assim, por mais que Tachibana-san seja ou não. <br/> - Não tinha como eu saber disso! <br/>- Ah tanto faz agora, mas o que vai fazer? <br/>- Vou conversar com ela depois. <br/>- Boa sorte então. Agora vamos voltar se não o professor vai brigar conosco. <br/>- Vamos lá, cagão! <br/>- Ei! <br/>- (risos)
    Depois de termos voltado à sala continuamos a assistir as aulas da manhã. Eu ainda pensava no que falar com Inaho, eu queria resolver logo todos os problemas e me desculpar. O tempo passou rápido e as aulas já tinham acabado.<br/>
   </h5><fieldset><a id="asteristico"> 13 Nota de web utilidade: (Facepalm) é a ação de bater com a palma no rosto em sinal de desaprovação, caso você não saiba. Procure por imagens no Google para melhorar sua compreensão.</a> </fieldset><div id="pagenum">Capítulo 5 – Irmão mais velho X Irmã mais velha. | 23 |</div> </div><div id="pages"><h5>

     Fui para a sala do clube me preparar para o treino e me encontrei com o Genji já pronto para jogar.<br/>
    - E aí capitão, pronto?<br/> - Quase Genji. Falta mais alguém chegar? <br/>- Acho que só falta o Ichigo.<br/> - De novo? Ele só chegar atrasa–  CHEGUEEEI! Hoje eu cheguei cedo. (Ichigo chega arfando)<br/> - Falando nele. <br/>- Hoje você não vai me mandar dar 10 voltas a mais capitão. Hoje não! <br/>- Muito bem, bem disciplinado você, parabéns. <br/>- Obrigado capitão (nunca corri tanto pra chegar a tempo) <br/>- Muito bem pessoal vamos nos aprontar que sábado será nosso amistoso contra a Seiho. Vamos mostrar para os atuais vice-campeões o lugar deles. <br/>- Eeeeeeeh! (todos)<br/>
    Hoje foi um dia inspirado, todos nós estávamos jogando conforme a regra. Passes certos, chutes certeiros e cruzamentos milimétricos. Durante a pausa vi uma pequena silhueta nas grades do campo. Quando me aproximei vi Murao Tachibana nos observando com olhos cheios de alegria.<br/>
    - Murao-kun venha aqui! Vamos jogar daqui a pouco, sente ali no banco.<br/> - Sério?<br/> - Claro. Vou te apresentar para o time, me acompanhe.<br/> - Legal! Ah onii-san posso te pedir uma coisa? <br/>- O que foi Murao-kun? <br/>- É que... Eu... Hum... Eu posso chamar você de aniki? (volte na página 7 e veja a nota que eu coloquei lá) - Por quê? - É que eu não tenho um irmão mais velho, só a onee-san. E eu sempre quis ter um irmão mais velho e chamá-lo assim. Eu posso? <br/>- Você confia tanto assim em mim pra me chamar de aniki?<br/> - Se você salvou minha irmã, jogou bola comigo ontem e fez meus pais te chamarem pra jantar lá em casa significa que você é confiável. <br/>- Wow muito obrigado Murao-kun! Então pode me chamar de aniki, será um prazer ter você com irmão mais novo. Agora vamos? <br/>- Sim aniki!<br/>


    Escutar aquele garoto me chamar assim e com um sorriso de satisfação no rosto me deu um sentimento novo. Acho que por ser irmão caçula eu nunca soube o que era cuidar de alguém mais novo, mas depois do Murao-kun me ter feito aquele pedido eu entendi.  Talvez ele só quisesse alguém para seguir assim como eu quando era pequeno. Eu ia com meu irmão a todos os lugares, ele me colocava em suas costas e conversava comigo todo o tempo. Mesmo quando ele estava com alguma garota ele sempre tirava um tempo pra ficar comigo. Não sei como é ter uma irmã mais velha, mas ter um irmão mais velho te deixa mais seguro. Levei Murao-kun para apresentá-lo ao time de futebol, mas ele mostrou ser meio tímido se escondendo atrás de mim, então tentei aliviar a situação.<br/></h5><div id="pagenum">Capítulo 5 – Irmão mais velho X Irmã mais velha. | 24 |</div> </div><div id="pages"><h5>
    - Pessoal eu quero apresentar alguém para vocês venham cá! Esse é Tachibana Murao. Ele está no Ginásio e gosta de jogar futebol. E hoje ele veio aqui pra jogar um pouco conosco. Vamos lá Murao-kun se apresente. <br/>- (envergonhado) É... É... É... É um prazer conhecer vocês, sou Tachibana Murao!
    Instantaneamente o pessoal foi se aproximando dele para deixá-lo mais confortável.<br/>
    - Oi Tachibana-kun o prazer é nosso! <br/>- E aí rapazinho que bom que você veio, vamos jogar! <br/>- Temos um recruta hoje! <br/>- E aí criança! <br/>- Não sou criança (Murao fala bravo) <br/>- Ui temo um hominho aqui! Toma um doce. <br/>- Ah obrigado!... Eei! <br/>- (risos)
    Ele já estava mais familiarizado com o pessoal. Genji vendo isso me chamou pra fora da roda.<br/>
    - O que foi Genji? <br/>- Por que trouxe o irmão da Tachibana pra cá? <br/>- Ele queira jogar bola comigo hoje, mas como eu falei que tinha treino e não dava ele acabou vindo pra cá. <br/>- Tem certeza que é uma boa ideia? <br/>- Qual o problema? <br/>- Ela pode não gostar depois do que aconteceu hoje. <br/>- Não se preocupe eu vou levá-lo daqui a pouco. Tachibana nem irá perceber. Agora vamos voltar para o treino.<br/>


    - Você que sabe capitão.<br/>
    Parece que o Genji estava certo quando ele disse isso não seria uma boa ideia. Dentro da escola no clube de Culinária as integrantes, entre elas a Tachibana, já estavam fechando as portas do clube para irem para casa.<br/>
    Susuki Keiko: - Inaho-chan você assistiu ao programa ontem? Eles cantaram tão bem ontem! <br/>- (...) <br/>- Inaho-chan? Está me escutando?<br/> - Hum? Perdão estava pensando em outra coisa. <br/>- O que aconteceu com você? Seu pensamento esteve longe hoje o dia todo. Mikage Asuna: <br/>- Verdade Inaho, hoje você está em outro planeta. Conte pra nós o que aconteceu. Está pensando no Sakamoto-kun? <br/>- Não, não, definitivamente não. Eu não gosto mais dele e me arrependo de ter gostado. É outra coisa que me incomoda. <br/>Asuna:- É o amigo dele. Takeyama-kun? <br/> </h5><div id="pagenum">Capítulo 5 – Irmão mais velho X Irmã mais velha. | 25 |</div> </div><div id="pages"><h5>- Quê? (fica corada quase que instantaneamente) <br/>- Sabia! Sua reação admitiu! Keiko:- Qual o problema Inaho-chan? Ele está importunando você? <br/>Asuna:- Ele nem é tão bonito assim. O que viu nele? <br/>Keiko:- Também não é assim Asuna-chan, ele é bonito sim, mas não chama a mesma atenção que Sakamoto-kun. Entre ele e Sakamoto eu o escolheria. <br/> Asuna: - Tanto faz <br/>Keiko, o problema não é se eles são bonitos ou não e sim o que o Takeyama-kun fez com a Inaho. <br/>Keiko: - Isso é verdade. Fala pra gente Inaho! <br/>- Meninas não foi nada demais, eu só me encontrei com ele hoje de manhã enquanto vinha pra cá. <br/>Asuna: - Só isso? - Sim. <br/>Asuna: - Estranho. <br/>Keiko: - Ei Inaho-chan, aquele não é o seu irmão? (olhando pela janela) <br/>- O quê? Murao? <br/>Keiko: - Acho que sim, veja. <br/>- Aonde? <br/>Keiko: - Ali no campo jogando com os meninos do clube de futebol. - Futebol? <br/>Keiko: - Isso está me cheirando a Takeyama Kaito. <br/>- Vamos lá garotas.<br/>


    Enquanto jogávamos Genji me avisou de um trio vindo em direção ao campo. Na frente delas a líder, Tachibana Inaho, fitava os olhos em mim com muita raiva. Quando elas chegaram ao alambrado eu pausei o jogo e fui „recepcioná-las‟.<br/>
    - Olá meninas em que posso ajudar? <br/>- O que meu irmão está fazendo aqui Takeyama? <br/>- Eu prometi que jogaria bola com ele hoje, mas por causa do treino não dava pra ser no parque, então ele disse que viria aqui. <br/>- Meu irmão não tem idade pra ficar andando pela cidade como se fosse o quintal de casa.<br/> - Mas a escola dele fica aqui perto. <br/>- (...) Tanto faz!  <br/>- Ele só queria jogar bola comigo qual o problema? <br/>- Você é o problema!<br/> - Eu?<br/> - Sim!<br/>
    Murao-kun vê nossa discussão e se aproxima para ver o que está acontecendo.<br/></h5><div id="pagenum">Capítulo 5 – Irmão mais velho X Irmã mais velha. | 26 |</div> </div><div id="pages"><h5>
    - Nee-san por que está brigando com o aniki?<br/> - “Aniki”? Como assim? Desde quando ele é seu irmão? (indignada) <br/>- Desde hoje nee-san. Takeyama-kun é um cara legal e não sei por que você só briga com ele. <br/>- Murao, Tachibana estamos fazendo um alvoroço aqui. Vamos para–  <br/>- Por que você está fazendo isso Takeyama? Me colocando contra o meu próprio irmão. <br/>- Eu não estou o colocando contra você! Ele só me pediu pra deixá-lo me chamar de aniki e nada mais.  <br/>- Vocês se conheceram ontem, como podem já ser amigos.<br/> - Por que só ontem ele brincou comigo mais do que você em minha vida inteira! (Murao grita quase chorando com Inaho) <br/>- O quê? (magoada)<br/>
    De longe Genji observa o que está acontecendo e pede para os outros jogadores não ficarem escutando a conversa dos outros. Lentamente ele vai recolhendo cada jogador. Por fim ele olha pra mim e diz algumas palavras, mas não as escutei por causa da distância. Porém sei o que ele disse. Algo do tipo “Eu lhe avisei que isso não daria certo”.  Murao saiu correndo do campo em direção ao jardim da escola. Nesse momento eu estava em um dilema: „Ficar ao lado da irmã ou ir atrás do irmão mais novo?‟ Decidi pelo caçula e fui em sua direção. Ao passar por Inaho ela disse: “(...) monstro!”. <br/>Aquelas    palavras mal ditas me deixaram com a impressão de que tinha feito algo horrível para ela. Acho que eu estava no mais fundo dos poços em relação a Inaho. Naquele momento ela devia me odiar mais do que qualquer coisa. Dentro do jardim Murao estava sentado embaixo uma árvore, sua feição era triste, mas ele não estava chorando. Fui tentar acalmá-lo.<br/>
    - O que aconteceu? <br/>- A nee-san, ela está sempre ocupada no quarto dela ou conversando com as amigas. <br/>- E ela não brinca com você? <br/>- Não!<br/> - Humm... Complicado. E você quer consertar isso? <br/>- Eu quero, eu quero brincar com ela pelo menos meia hora. <br/>- Difícil acreditar nisso, eu não sabia que ela era assim. <br/>- Mas mamãe diz que a culpa não é dela.<br/> - Como assim? <br/>- Não sei dizer direito, mas parece que tem algo a ver comigo. Nee-san cuida bem de mim quando nossos pais não estão, mas ela não fica muito tempo comigo. <br/>- Ela deve saber o que aconteceu. Vamos voltar agora? Está ficando tarde e você tem que ir pra casa. Não quero causar mais problemas. <br/>- Vamos aniki. <br/></h5><div id="pagenum">Capítulo 5 – Irmão mais velho X Irmã mais velha. | 27 |</div> </div><div id="pages"><h5>- Eu te levo.<br/> - Legal! Vamos, vamos! <br/>- Se não estivesse perto da hora do jantar eu compraria um picolé pra você (risos). Vou pegar minha bolsa na sala do clube e já vamos. Me espere na saída. <br/>- Entendido!<br/>
    Voltando para o campo de futebol vi Inaho e suas amigas sentadas na grama. Ela estava visivelmente triste e em silêncio. Eu gostaria de saber o que havia entre os irmãos, mas não sabia se seria o correto me envolver tanto. Talvez eu pudesse ajudar, porém é melhor ir com calma. Aproximei-me das garotas e falei diretamente com Inaho.<br/>
    - Tachibana-san, preciso conversar com você! <br/>- O que foi Takeyama? O que vai fazer agora, tirar minhas amigas de mim? - Eu não sou esse tipo de pessoa que você imagina.<br/> - Então o que você quer? <br/>- Hoje, ás dezenove horas embaixo da cerejeira. Preciso conversar com você!<br/>


    Eu não sei o que está acontecendo comigo hoje, mas estou muito mais imprevisível do que nunca. Em que mundo eu seria tão direto com uma garota, e ainda por cima a garota que gosto. O assunto era grave, um problema familiar, e eu sentia que deveria ajudar, por isso queria conversar com ela. Continuei explicando:<br/>
    - Estarei te esperando lá. <br/>- O-o-o-o que você quer conversar comigo lá? <br/>- Lá eu te explicarei. Vou levar seu irmão embora. <br/>- (abaixa a cabeça e concorda) Tudo bem. <br/>- Vamos parar com nossas brigas por enquanto. <br/>- Tudo bem. <br/>- Estou de saída. <br/>- Tchau. <br/>- Tchau (Keiko e Asuna balançam as mãos surpresas com a ação de Kaito)<br/>
    Tinha de avisar as Genji que estava de saída, pegar minhas coisas e encontrar Murao.<br/>
    - GENJI! <br/>- Sim capitão! <br/>- Vou embora, por que tenho que levar Murao em casa então finalize o treino com alguns exercícios de recuperação. Fale com os rapazes que se ganharmos a partida sábado iremos as termas. <br/>- Que jeito de motivar os rapazes, mas tudo bem. <br/>- Obrigado Gen (me virando). <br/>- Eu falei que ia dar problema. <br/>- Eu sei, mas eu vou resolver isso tudo. <br/>- Assim espero! E não esqueça que a partida é sábado, ou seja, não deixe essa semana prejudicar nosso time. <br/>- Sem problemas! Bom trabalho e tchau! <br/>- Bom trabalho e nos vemos amanhã<sup>14</sup>.<br/>
    Depois de ter me trocado fui em direção ao portão da escola e encontrei Murao sentado em um banco perto do portão. O chamei e andamos em direção as nossas casas. Em nosso percurso passamos por vários lugares que chamava a atenção do pequeno.      <br/>                                           </h5><fieldset> <a id="asteristico">14 Nota: É costume dos japoneses ao concluir uma atividade dizerem essa expressão “Bom trabalho” como forma de agradecer aos serviços que cada um prestou. Porém caso fosse uma escrita em japonês original a forma como o Genji e Kaito se despedem seriam diferentes, por exemplo, Kaito por ser o capitão logo o superior, diria Gokurousama (ご苦労様). Em comparação Genji usaria Otsukaresama (お疲れ様) por ser um “subordinado”.</a></fieldset><br/>
    </h5><div id="pagenum">Capítulo 5 – Irmão mais velho X Irmã mais velha. | 29 |</div> </div><div id="pages"><h5>

    Esperando no semáforo, o mesmo em que Inaho quase foi atropelada, ele olhava para os lados vendo se era seguro, muito diferente da irmã.  Quando o semáforo abriu para os pedestres comecei a andar, no mesmo instante senti um puxão em minha camisa. Era Murao a segurando para me acompanhar pela faixa de pedestres. Aquele gesto me tocou e seguindo o contexto dei a minha mão para ele segurar, eu não sabia se era isso o que tinha de fazer, mas fiz. O pequeno segurou firme e cruzamos a faixa. Do outro lado da rua soltei sua mão e lhe sugeri algo mais conveniente.<br/>
    - Que tal subir em minhas costas?<br/>
    Pela expressão dele eu acho que ele gostou então a partir dali fomos pelo caminho mais curto para adiantar a chegada dele. No nosso ponto de separação resolvi o deixar em casa para explicar o atraso dele. Não queria deixar um mal entendido para a família. Toquei a campainha e esperamos do lado de fora. Uma senhora de uns 40 anos abre a porta, provavelmente a mãe dos irmãos Tachibana.<br/>
    - Filho, que demora! Onde esteve? <br/>- Desculpe mãe. <br/>- E quem é o rapaz? Pelo uniforme é da mesma escola que Inaho. O que aconteceu? <br/>- Prazer em conhecer a senhora, sou Takeyama Kaito, colega da Tachibanasan. Vim trazer seu filho e pedir desculpas por chegar tão tarde. <br/>- Takeyama? Um momento, você o rapaz que salvou minha filha? <br/>- Sim, senhora! (envergonhado) <br/>- Óóh que emoção! Que oportunidade é essa! Vamos entre! (eufórica) <br/>- Eu agradeço muitíssimo pelo convite, mas minha mãe me espera para o jantar. Eu só queria explicar que Murao-kun foi a minha escola por que prometi a ele que jogaríamos futebol, mas acabamos nos empolgando e ficando além do combinado. <br/>- Meu jovem eu fico contente em saber que ele estava com você e que está tudo bem com vocês. E eu entendo sobre você não poder ficar, mas sábado estarei lhe esperando. Certo? <br/>- Virei com certeza! Teremos um jogo pela manhã, mas antes do almoço estarei aqui. Ah! Vou aproveitar a oportunidade e convidar você, Murao para assistir o jogo. Venha assistir, ok? <br/>- Posso mãe? <br/>- Se você arranjar alguém pra ir com você. <br/>- Hummm... <br/>- Chame sua irmã Murao-kun. Ela vai querer ir contigo com certeza.<br/>


    A mãe me olha com um olhar querendo me tirar as esperanças.<br/>
    - Quem sabe, não é Murao? <br/>- Vou tentar chama-la mamãe. <br/>- Isso mesmo, você tem de tentar.<br/>
    De início eu não entendia o que estava acontecendo, mas eu sabia que tinha algo de errado acontecendo. Espero que quando encontrar Inaho, ela me explique qual o problema com seu irmão. Agora tenho de me apressar e tomar um banho para ir ao parque.<br/>
    - Vou embora agora, vejo você depois Murao-kun. Boa noite! <br/>- Tchau aniki, boa noite. Obrigado por hoje! <br/>- Boa noite Takeyama-kun, tome cuidado. <br/>- Obrigado, até mais.<br/></h5><div id="pagenum">Capítulo 5 – Irmão mais velho X Irmã mais velha. | 30 |</div> </div><div id="pages"><h5>
    No caminho antes de virar a esquina em direção a minha casa vi a certa distância uma jovem senhorita caminhando a passos lentos e firmes em minha direção. Inaho não olhava em minha direção, apenas seguia seu rumo. Em certo momento ela notou minha presença, mas disfarçou o olhar como que evitando ter contato comigo. Disse em voz baixa: “Estarei lhe esperando.”, porém ela não demonstrou reação. Chegando em casa encontrei minha mãe na cozinha preparando o jantar, mas não vi meu irmão, e depois de perguntar por ele, mamãe respondeu que ele estava em uma reunião com os diretores da clínica que estavam interessado nele. Fiquei feliz pelo meu irmão que estava realizando um dos seus sonhos. Subi para meu quarto e depois tomei um banho para relaxar. Eu estava ansioso pelo encontro com Inaho e... Espera! Um encontro? Eu estava prestes a ter um encontro com Inaho... Não! Não era esse tipo de encontro. Meu objetivo é saber o que acontece entre ela e seu irmão e nada mais. Ás seis horas da noite meu pai e meu irmão chegaram praticamente juntos. Então desci e me aprontei para jantar. Porém meu pai e meu irmão queriam tomar banho antes. Mas eu estava nervoso e queria sair logo, então jantei primeiro e saí. Quando eles desceram perguntaram por mim mamãe respondeu que tinha ido encontrar alguém. Os dois se olharam e fizeram aquela cara de „Eu sei quem ele foi encontrar‟. Andando em direção ao parque meu celular começa a tocar. Era Genji me ligando.
    - Alô? - Oi Taka, Tá fazendo o quê? - Estou indo no parque. - Fazer o quê?<br/>


    - Encontrar com a Inaho. <br/>- O QUÊ?!<br/> - Vou pedir a ela que me explique o problema entre ela e seu irmão. Estou um pouco intrigado com isso. <br/>- Eu sabia que deixar o garoto tão próximo não seria bom. Ainda mais depois do que você falou com ela hoje. - Eu não falei nada demais. E além do mais a culpa é dela, mas o importante não é isso. <br/>- Então Tá. E você acha que ela virá te encontrar?<br/> - Vem sim, tenho certeza! <br/>- Ótimo! E mais uma coisa. <br/>- O que foi? <br/>- Me empresta sua atividade de Física? *desliga o telefone* <br/>- Ei, ei Taka! Miserável!<br/>
    Cheguei dez minutos mais cedo e esperei sentado no balanço. O horário marcado chegou e ela ainda não tinha chegado, fui a uma loja de conveniência e comprei algo para beber. Dez minutos se passaram e enquanto eu escutava música balançava no brinquedo. Então percebi que alguém se aproximava do parque. Quando ela se aproximou da luz eu vi uma garota com um moletom, um short e um tênis estilo all star. Ela usava um rabo de cavalo e ÓCULOS! Eu não sabia que ela usava óculos, mas mesmo ela ficava linda de óculos. (Imagine Kaito olhando para Inaho com cara de besta apaixonado)<br/>
    - O que foi? (perguntou rispidamente) <br/>- Nada, é que eu não sabia que você usava óculos. <br/>- Óculos? Ah droga me esqueci de tirar essa coisa (tirando os óculos). <br/>- Não tire, por favor. Se você usa é por que precisa. <br/>- Não é pra tanto, são só pra descanso. <br/>- Mesmo assim. <br/>- Está bom (põe de volta). O que você quer conversar comigo? <br/>- Algo que me deixou incomodado e muito. <br/>- Foi o que aconteceu agora à tarde? <br/>- Sim. <br/>- Eu acho que você não vai entender. <br/>- Por quê? <br/>- Você tem irmãos?<br/> - Um mais velho. <br/>- E como vocês se dão? <br/>- Muito bem.


    - Talvez você não entenda. <br/>- Vou fazer o possível pra entender. <br/>- Ah como você é insistente!<br/> - Na verdade sou mais curioso. <br/>- Não posso demorar, então vou começar logo. (sentando no outro balanço) <br/>- Pra você. (lhe entrego uma sacola com uma latinha de suco) <br/>- Surpreendente você (pega a sacola). Por onde devo começar? <br/>- Me fale sobre sua relação com seu otouto15. <br/>- É algo meio complicado de explicar pra alguém que não conhece minha família. <br/>- Seja simples e objetiva. <br/>- Deixe-me acalmar um pouco. (respirando fundo) <br/>- Fique a vontade.  <br/>- Então...</h5><div id="pagenum">Capítulo 5 – Irmão mais velho X Irmã mais velha. | 31 |</div>

</div>
<?php $back="Cap #4"; $next="Cap #6"; $backs="?cap=4"; $nexts="?cap=6"?>