<meta charset="UTF-8"/>
<style>div#main{margin-top: -115px}</style>
<div id="pagesfd">
    <h2>Paradox Love</h2>
    <h4>Capítulo 6 – Transforme os receios em coragem.</h4>
<h5>
    Depois da discussão a beira do campo naquela tarde, fiquei intrigado pela relação seca entre os irmãos Tachibana. Inaho não tratava bem o irmão e isso afetava, e muito sua relação. Eu sei que poderia ajudar de algum jeito por isso a chamei para uma conversa no mesmo parque onde conheci seu irmão. Ela começou a me contar sobre o relacionamento deles.<br/>
    - Então... Eu gosto muito do meu irmão, mas eu tenho medo de me aproximar dele.<br/> - Por quê? <br/> - Você já sabe que eu não sou a pessoa com a melhor coordenação motora e que também não presto muita atenção em algumas coisas ao redor. <br/>- Verdade. (percebi bem) <br/>- Pois então, foi por causa dessas características que não me aproximo do meu irmão. <br/>- Só por isso? Não tem mais nada? <br/>- Calma, é difícil falar sobre isso! <br/>- Perdão. (abaixa a cabeça) Prossiga. <br/>- Quando Murao estava pra nascer mamãe sofreu um acidente em casa, ela caiu da escada. Papai estava no trabalho e eu tinha acabado de chegar da escola. Quando vi mamãe gritando de dor eu me desesperei, eu só tinha oito anos, não sabia o que fazer. Eu corri pela casa tentando achar alguma coisa pra ela, mas enquanto eu me desesperava ela agarrou minha mão e disse: <br/>                                                15Nota: (Otouto) significa “irmão mais novo”.<br/>


    “Ligue pro papai, ele sabe o que fazer!”, e assim eu fiz. Papai chamou uma ambulância e veio correndo pra casa socorrê-la. Eu fiquei com muito medo naquela hora, não sabia se estava tudo bem com ela e meu irmão, eu só orava a Deus para que tudo desse certo. - E o que aconteceu depois?  - Murao nasceu saudável e sem nenhuma complicação.  - E depois? Como foi sua recepção ao Murao? - Eu fiquei feliz por ter um irmão mais novo, mas eu estava tão arrependida que sequer olhei pra ele. Confesso que tive muito medo naquela hora em que vi mamãe desmaiada, mas aliviada quando os dois entraram pela porta. Mas sempre o achei muito frágil por ser tão pequeno. - Então é por esse motivo que você evita o seu irmão? - Esse não foi o maior dos problemas. Eu fui muito desajeitada com ele em nossa infância, fiz coisas piores que me deram esse medo de me aproximar dele. - Quer me contar? - (silêncio) - Se não quiser tudo bem. - Eu falo. Como eu começo? É difícil, mas tudo bem. Mamãe uma vez me pediu para aquecer a água para dar banho nele e se ela não tivesse verificado eu teria cozinhado meu irmão. Outra vez eu deixei a janela do quarto dele aberta, por que achei que estava quente. Caso papai não tivesse ido vê-lo ele teria pegado uma pneumonia, pois começou a chover forte na mesma noite. Em outra situação mamãe me deixou tomando conta dele no supermercado enquanto ela pegava alguma coisa que tinha esquecido. A moça que embala as compras me salvou, por que ele quase foi levado pra outra cidade em uma caixa que ele tinha entrado. Meus pais brigaram muito comigo e eu acabei me distanciando dele com medo de deixar coisas piores acontecerem. Eu só fazia coisas necessárias como dar algo para comer. - (Parabéns Murao, estar vivo é um presente para você. Mesmo assim você ainda ama sua irmã. Que amor fraternal) Agora eu entendo você! Ter passado por tantas situações como essas também me deixariam traumatizado (caso eu fosse o Murao).  - É essa a sensação! - Você quer resolver isso? - Quero, mas não sei como. - Você me deixaria ajudá-la? - Por que você quer ajudar? - Por que eu tenho um irmão mais velho e sei como é bom ter a atenção dele. E é isso que o seu irmão quer. Atenção e carinho vindos de você.

    Capítulo: Capítulo 6 – Transforme os receios em coragem 47
    - E como você pretende ajudar? - Um tempo juntos! - Hãm?  - Sábado de manhã, leve seu irmão para assistir nosso jogo treino. Ele gosta de futebol e aproveitem para tomar um sorvete juntos. Deixe-o a vontade perto de você e não force muito as conversas. - Será que vai dar certo? - Como vocês nunca fizeram nada juntos qualquer coisa que fizerem o deixará feliz. - Talvez seja uma boa ideia, mas ainda tenho medo de não saber o que fazer. - Mantenha a calma e aja como se estivesse com suas amigas, seja natural. - Vou me esforçar. - Vou torcer pra tudo dar certo, mas quero algo em troca. - O quê? Então é esse o motivo de você estar me ajudando? Seu oportunista! - Não, não é isso! Não é nada demais, eu só quero que vocês torçam por mim durante o jogo de sábado. - Ah é isso? (sem graça) - Sim, eu vou ficar feliz em vê-los lá no campo. - Verdade? - Claro! (sorriso enorme) - Então tudo bem (falando baixo com biquinho), nós iremos. - Ótimo! Já cumpri meu objetivo, vamos embora? (levanta do balanço) - Vamos (também levanta). Muito obrigada Takeyama-kun, vou me esforçar para dar tudo certo entre Murao e eu. Não quero desperdiçar sua ajuda. - Jogue duro! Conte-me tudo depois, ok? - Pode deix...– (tropeça enquanto caminha) - CUIDADO! (a seguro pela cintura e seguro sua mão quase a abraçando (AGI TOTALMENTE POR REFLEXO!)) Está tudo bem contigo? - S – S – Sim...! (corada) - Que bom, tome mais cuidado. - Pode deixar, mas poderia... (caham)... me soltar? - (corado) Sim, claro! Agora! (a solto) - Vamos pra casa né? Hoje o dia foi cansativo e ambos precisamos descansar. - Concordo com você Tachibana-san. - Quanto ao meu nome você pode me chamar de Inaho, acho que não tem problema. - (silêncio)... Então pode me chamar de Kaito se quiser. - Posso? - Sim, confesso que fiquei um pouco surpreso. - Excelente! Já está ficando tarde, nos vemos amanhã. Boa noite.

    Capítulo: Capítulo 6 – Transforme os receios em coragem 48
    - Só mais uma coisa. Esforce-se se você quer dar um fim ao seu medo. Seu irmão já não é tão frágil e você não é mais uma criança. Entende-me? - Sim, e mais uma vez muito obrigada. Boa noite! (sorri pra mim) - B-Boa noite e tenha cuidado! (corado por causa do sorriso dela)
    Despedimo-nos e fomos em direção a nossas casas. Quando a perdi de vista me lembrei da sensação de quando segurei a sua mão. Era pequena e quente e me passava um sentimento de segurança. Queria segurá-la de novo e de novo por quantas vezes eu pudesse e isso me deixava cada vez mais apaixonado por ela. Sapporo16, como sempre, estava bem fria, então eu estava louco por um banho quente e ir direto para cama. Quando cheguei em casa vi meu irmão na cozinha de novo lendo vários documentos, fiquei curioso e lhe fiz uma pergunta:
    - Trabalho de novo? - Lá vem você com essa curiosidade! - Qual o mal em perguntar? - (risos) Nenhum, e sim, são da empresa. É uma nova pesquisa que estão fazendo e me colocaram na equipe como auxiliar. - Está gostando do novo trabalho?  - Por enquanto minhas expectativas foram atendidas. - Que bom! - Quer chá? Mamãe fez para nós. Ela imaginou que você fosse querer. - Claro, vou pegar uma xícara. (se serve e senta a mesa) - O que foi? Parece inquieto. - Eu tenho uma pergunta. - Qual? - Você já teve medo de deixar alguma coisa acontecer comigo quando eu era pequeno? - Wow que repentino! Deixe-me lembrar (pensa)... Sim, teve uma ocasião. - Qual? - Você tinha uns dois anos quando uma vez você subiu no armário pra pegar uns biscoitos ou algo assim e a mamãe me deixou tomando conta de você enquanto ela lava a roupa. - Eu fiz isso?! - Sim, e quando eu o vi lá em cima eu saí desesperado atrás de futons17pra colocar embaixo do armário caso você caísse, mas mamãe chegou bem na hora e gritou comigo enquanto pegava você.
    16Nota informativa: Sapporo é a cidade onde se passa a história. Mais informações Wikipédia.org 17Nota de conforto: Um futon (布団, futon) é um tipo de colchão usado na tradicional cama japonesa. Fonte: Wikipedia.org

    Capítulo: Capítulo 6 – Transforme os receios em coragem 49
    - Eu fiz isso? - Fez coisas piores, mas essa foi a vez que mais fiquei assustado. Mas por que esse assunto? - Uma dúvida que tive, mas você já respondeu. Vou tomar um banho e dar uma estudada. Boa noite irmão. - Boa noite Taka. E mais uma coisa. - O que? - Aquele dia em que você subiu no armário meu medo maior não foi ver você quebrar algo ou pela surra que eu levaria da mamãe e sim acontecer algo muito mais grave. Eu não suportaria perder alguém que eu vi crescer. Entende? - Sim irmão (feliz), muito obrigado! - Boa noite!
    Conversar com meu irmão quando tenho dúvidas sempre me deixa aliviado. Ele responde minhas desconfianças com poucas palavras e ás vezes nem precisa saber do assunto. Acho que essa é uma boa relação entre irmãos e é isso que Inaho tem que alcançar. Enquanto estudava um pequeno flashback veio a minha mente. Voltei ao dia do quase acidente, pra ser mais preciso no momento em que abracei a Inaho, e de repente fui levado para o parque no momento em que segurei sua mão para evitar sua queda.
    - Preciso dormir!
    Arrumei minha bolsa e fui para cama, mas aquela sensação vinha a minha mente a todo instante, e de repente uma pergunta veio em minha mente: Será que ela sentiu alguma coisa quando segurei em sua mão, ou pra ela foi algo normal? Não sei responder.
    ** MAS EU SEI (AUTOR) **
    – Visão da Inaho –
    Ao nos despedir um sentimento estranho tomou conta do meu peito. Minha mente vagueou até voltar ao dia do acidente. Senti uma mão forte me agarrando e logo depois algo me encobriu. Senti-me segura por mais que eu não soubesse o que estava acontecendo. E hoje senti a mesma sensação quando ele me segurou no parque. Suas  mãos firmes me envolveram e ao mesmo tempo eu sentia o calor delas.  Pensar nisso me deixava apreensiva e insegura. Será que gosto do Kaito? Não, não posso! Isso seria repentino demais. Afinal, eu o conheci praticamente há três dias. Que tipo de garota eu sou? Ele é só um novo amigo não posso gostar dele em tão pouco

    Capítulo: Capítulo 6 – Transforme os receios em coragem 50
    tempo. Vou parar de pensar nisso, ele é só meu NOVO AMIGO! Hoje está frio, um chocolate quente cairia muito bem. Chegando em casa vi meus pais assistindo televisão, então fui para a cozinha preparar meu chocolate quente. Peguei os ingredientes e comecei a fazer. 15 minutos depois servi a mim e a meus pais, mamãe se aproximou e me disse:
    - Quer que eu leve pro seu irmão?
    As palavras de mamãe me lembraram da conversa com Kaito no parque e percebi que tinha de mudar meu comportamento. Respondi a mamãe que eu levaria e ela obviamente ficou surpresa, por que eu não fazia nada, nesse sentido, pelo meu irmão.  Subi as escadas e bati na porta do quarto do meu irmão, mas ele não respondeu. Abri lentamente a porta e o vi sentado em sua mesa de estudos debruçado sobre os livros. Aproximei-me lentamente e coloquei o chocolate quente na mesa e o observei dormindo. Ele parecia tão inocente. E subitamente me veio uma vontade de abraçá-lo, mas me contive com um cafuné em sua cabeça e um pequeno bilhete perto da caneca.  O deixei dormindo e fui para meu quarto estudar e fazer outras coisas. Pouco tempo depois Asuna me ligou:
    - Oi Inaho! - Ooi! O que foi? - Eu sempre te ligo, poderia pelo menos me recepcionar melhor. - Oi coisinha fofa da mamãe! Tudo bem com você? - Falsa. - Estranha você. Se eu sou sincera você reclama, quando minto também.  - Isso não vem ao caso, eu quero saber do encontro com o garotão! Conte-me. - Onde está a Keiko? Quero falar pras duas. - Um momento. Vou fazer a ligação em grupo (com a tecnologia hoje isso é possível). - Tudo bem. *momentos depois* Asuna: - Pronto, as três estão aqui! Keiko: - Oi Inaho-chan! Inaho: - Olá meninas! Asuna: - Agora nos conte como foi! Inaho: - O que vocês acham que aconteceu? Asuna: - Vocês andaram de mãos dadas, trocaram beijinhos. Keiko: - Não seja inocente Asuna-chan, é claro que a Inaho não faria isso. Desculpe a mente pervertida dela Inaho-chan. Inaho: - (risos) Claro. Afinal, essa é a Asuna que conhecemos. (mais risos)

    Capítulo: Capítulo 6 – Transforme os receios em coragem 51
    Asuna: - Eeeei! Inaho e Keiko: (risos) Inaho: - Não foi nada demais, ele só me ajudou com um problema complicado. Asuna: - Qual foi o problema? Keiko: - Asuna-san seja discreta. Se ela quisesse ela falaria. É algo que Takeyama-kun e Inaho-chan sabem. Asuna: - Ah, mas eu quero saber! Inaho: - Calma, em outra oportunidade eu falo. Keiko: - Responda-me duas perguntas. Ele gosta de você Inaho-chan? Inaho: - O QUÊ?! (surpresa quase engasgando) Que pergunta é essa? Keiko: - Só responda. Inaho: - Eu não sei! Keiko: - Fale a verdade! Inaho: - Aaaah!!! Keiko: - Ele gosta de você! Que bonitinho! Agora a outra pergunta: Você está gostando dele? Inaho: - Q-Q-QUÊ?! De onde você está tirando essas perguntas?  Keiko: - Qual o problema? Afinal somos jovens e estamos na primavera. Todos têm o direito de amar! Inaho: - Mas não é assim que as coisas fluem. Além do mais eu acabei de me confessar pro Sakamoto-kun e ser rejeitada por ele, começar a gostar do Kaito do nada seria um atestado de futilidade. Asuna: - “Kaito”? Já estão assim? Keiko: - Fico feliz por pensar assim. Inaho: - Por quê? Keiko: - Não acha quer seria injusto isso? Colocar Takeyama-kun no buraco causado por Sakamoto Genji?
    As palavras da Keiko ressoaram em minha mente no mesmo instante. O que eu sentia por Genji era amor? E o que eu sinto por Kaito? Minha consciência começou a pesar e a me encher de dúvidas. Terminei a conversa por ali.
    Inaho: - Seria injusto mesmo Keiko-san, ele é muito legal. Vou dormir agora. Afinal, hoje foi um dia cheio. Boa noite. (voz triste) Asuna: - Boa noite Inaho, durma bem! Keiko: - Bons sonhos Inaho-chan, até amanhã. *Inaho desliga* Keiko: - Asuna-chan, antes de desligar... Asuna: - O que foi?

    Capítulo: Capítulo 6 – Transforme os receios em coragem 52
    Keiko: - O que acha que está acontecendo com Inaho? Asuna: - Não sei dizer. E essa semana está complicada pra ela, a cabeça dela deve estar cheia. Mas o que você acha que está acontecendo? Keiko: - Pelo que conheço dela eu acho que ela está em dúvidas, mas isso é normal. Todos nós, adolescentes, temos dúvidas. E agora ela vai pensar bastante. Asuna: - Você é do mal, sabia? Keiko: - Só espero é que ela não se machuque e não machuque Takeyamakun. É só isso que quero. Asuna: - Acho que sei aonde que chegar. Vou desligar boa noite! Keiko: - E seu namorado? Asuna: - Conversamos mais cedo. Keiko: - Ok, então boa noite! Asuna: - Até amanhã! *ambas desligam*
    Deitada em minha cama meditei nas palavras da Keiko e minhas dúvidas só aumentavam em relação ao Kaito. Eu tenho certeza que não é normal alguém deixar de gostar uma pessoa e logo depois gosta de outra. Não há lógica! Ou será que... (reflexão) eu nunca gostei do Sakamoto-kun? Eu o admirava e sempre o achei muito bonito, mas será que eu gostava mesmo dele? Aaaaaah! (abafa o grito com o travesseiro) Isso é muito complicado, eu não consigo chegar a uma conclusão. Será que eu gostava mesmo dele? Ou eu só queria a atenção de um garoto popular? Não posso ficar tapando o sol com uma peneira, ou seja, achar que está tudo bem e começar a criar desculpas. Isso só mostra como sou ingênua. Que deplorável! Acho melhor ir dormir e tentar esfriar a cabeça.
    *pela manhã*
    Depois de uma noite de sono não tão bem dormida me arrumei e desci para tomar café. Meus pais já estavam tomando café e Murao ainda não havia descido.
    - Bom dia pai e mãe. - Bom dia filha. - Bom dia minha filha. Que rosto de cansaço é esse? Dormindo pouco? - Talvez. - Hum. Sente e tome seu café, quem sabe você não melhora.  - (puxa a cadeira) Assim espero. E onde está o Murao?

    Capítulo: Capítulo 6 – Transforme os receios em coragem 53
    No mesmo instante me assusto com alguém cutucando o meu ombro.
    - Bom dia Nee-san! (da um sorriso enorme enquanto segura o bilhete) - B-Bom dia Murao. - Muito obrigado pelo chocolate quente ontem e também pelo bilhete. - Bilhete? (disse papai surpreso) - Sim. Olha! (o mostra pra papai) - “Se esforce ”? Sua irmã que escreveu isso? (olha rapidamente pra mim e pra mamãe) - Sim, foi ela! - Filha como estou orgulhoso de você! - Oi? - Você está mudando, minha filha, e isso é bom. - Ah! Estou? (coçando a bochecha envergonhada) - Nee-san eu vou guardar com muito carinho esse bilhete. - Sério? Tudo bem então. (preciso tomar coragem e falar agora) aproveitando o momento o que acha de assistirmos o jogo do Takeyama-kun amanhã? - O QUE?! (pai e mãe) Que dia mais feliz!! - (assustada) O que foi? - O que aconteceu com você? Que mudança repentina a sua! - Pensei muito em minhas atitudes.  - Será a primavera?18 - NÃO, NÃO E NÃO!! (muito envergonhada) - Não minta pra sua mãe. - Vamos deixar isso de lado por agora. Murao quer ir comigo? - Claro! Eu quero ver o aniki jogando e também quero sair com você nee-san. - Está marcado. (como Kaito disse, eu tenho de dar um fim as nossas diferenças e ao meu medo) - Vamos tomar café. Itadakimasu!19
    – Visão do Kaito –
    Na manhã seguinte, já a caminho da escola, eu estava com a mente um pouco cansada por causa dos últimos acontecimentos e também pelos eventos que me aguardavam. (o jogo de amanhã e o jantar na casa da Inaho) Eu precisava me concentrar
    18Nota romântica: No Japão a primavera é a estação do florescer das novas paixões.  19Nota de fome: „Itadakimasu’ é uma expressão de agradecimento pela comida, ou seja, “Obrigado pela comida”.

    Capítulo: Capítulo 6 – Transforme os receios em coragem 54
    na partida, por mais que fosse um amistoso, contra a Seiho. Afinal, eles eram os vices do campeonato do ano passado.  Durante as aulas eu não estava ao atento quanto deveria estar e o tempo parecia não passar, ou seja, eu estava tão cansado que conseguia parar o tempo. Quando a última aula da manhã acabou corri para a cafeteria pra comprar meu lanche. Depois fui para um lugar aonde eu poderia descansar um pouco e de preferência com um pouco de sol. O terraço do clube de astronomia era perfeito, porém era fechado para quem não era integrante. Mas um dos integrantes é meu amigo (Kushida Shiro) e me emprestou a chave, visto que no dia o clube não teria atividades naquele dia eu não incomodaria ninguém e vice-versa. Do terraço eu observava a quantidade de casais pelo pátio, àquela cena era um pouco deprimente para um jovem solteiro. Pra não perder a fome mudei de lugar, e enquanto comia meu sanduíche eu vi uma cena que me fez perder um pouco a noção. Inaho e suas amigas lanchando.  Como sempre estava linda e com um belo sorriso e com uma fome invejável. De certa forma eu estava me sentindo melhor por vê-la sorrindo, poderia ser um bom sinal. Parecia que algo havia chamado a atenção dela para cima o que a fez olhar direto pra mim. Eu me espantei pelo olhar direto dela, ela então sorriu e acenou para mim, porém eu fiquei tão envergonhado que acabei não respondendo e saí de cena.  Depois de comer me deitei para descansar um pouco perto da caixa d‟água. A sombra feita por ela era confortável e por isso acabei fechando os olhos e cochilando. Durante o sono acabei sonhando com o jogo da final no campeonato nacional. No último lance o jogo estava empatado e eu estava com a bola indo em direção ao gol adversário e só havia o goleiro em minha frente. Cara a cara com ele o driblei, mas no último momento meu ar acabou. Isso mesmo, eu não conseguia respirar. Subitamente eu acordei e percebi que uma mão tampava meu nariz. Acordei agoniado e puxando muito ar. Olhei para os lados e uma garota estava sentada ao meu lado sorrindo. Quando me acalmei olhei melhor a feição alegre de quem quase me matou. Aquela foi apenas uma das tentativas da Inaho de me acordar. E obviamente eu não estava feliz com aquilo. Briguei com ela.
    - Por que fez isso? - Você estava tão bonitinho dormindo! - (corado) Q-Q-Quê? - Não fique envergonhado. Seu sono estava muito bom. - Como sabe? - Tentei te acordar de todos os jeitos. Fiz cócegas, tapinhas na cara, te balancei, dei alguns chutes, mas sem resultados. E você estava até sorrindo enquanto dormia. - Sério? (ainda corado)

    Capítulo: Capítulo 6 – Transforme os receios em coragem 55
    - Sim. - Que hora é agora? - A primeira aula já está quase acabando. - DORMI TANTO TEMPO ASSIM? - Sim, mas você precisava. Pela sua cara de hoje pela manhã o seu cansaço era evidente. Mas não se preocupe, por que esse horário é aberto para estudos.  - Dei muita sorte então, por que se Natsu sensei soubesse dessa falta eu estaria fora da partida. - Sério? - Sim. - Bem rígido ele. - Pois é, mas você veio aqui só me avisar? - Não, eu já estava aqui antes. A Asuna me enviou uma mensagem falando do horário vago. - Ou seja, se estivéssemos em aula você estaria matando aula comigo? - Mais ou menos. Eu trouxe pra você (me entrega uma latinha de café), acho que é o que você gosta. - O – Obrigado. (tímido) - Estou pagando o favor de ontem. - (risos) E o que lhe traz aqui? - Queira agradecer por ontem. Consegui falar com meu irmão e convidá-lo pro jogo de amanhã. - Que ótimo! - Consegui enfrentar meu medo graças ao que você me disse. Ele já não é tão frágil e eu já não sou uma criança. Acho que agora as coisas podem dar certo. - Isso é ótimo! Eu realmente quero que tudo dê certo entre vocês. - Que assim seja. Vamos voltar? - Vamos. O horário vago deve estar acabando. - Ok! (levanta) Vamos! (estende a mão para mim) - Obrigado! (seguro sua mão)
    No momento em que me impulsiono para subir percebo que ela é mais leve do que imaginei e acabei puxando ela pra baixo. Caindo em cima de mim ficamos em uma posição não muito confortável e com certeza muito constrangedora. Enquanto nos ajeitávamos para levantar Genji abre a porta e procura por mim. Sua reação:
    - Taka, seu–... Opa, perdão não queria atrapalhar. Com liceeeençaa! (fecha a porta lentamente)

    Capítulo: Capítulo 6 – Transforme os receios em coragem 56
    Rapidamente nos levantamos e nos aprontamos para descer. Ficamos com tanta vergonha que não conseguíamos nos olhar.
    - Me desculpa, acho que lhe puxei forte demais. - T-T-Tudo bem, só tome mais cuidado. Eu sou uma garota. - Pode deixar. - Pegue seu lixo. (brigando comigo) - Ãhm? Ah claro! (pegando a latinha e o plástico do sanduíche)
    Após trancar a porta descemos as escadas em um silêncio estarrecedor. Caminhando pelo corredor, parei e disse a ela:
    - Vou entregar a chave ao Shiro. Pode ir sem mim? - Sim, posso. (tímida) - Até mais. - Até.
    Depois de entregar a chave ao Shiro voltei para a sala para assistir as últimas aulas da tarde. No fim das aulas Genji e eu fomos para a sala do clube nos trocar. No caminho para ela eu estava em silêncio e com um bico enorme. Porém Genji estava no total oposto, ele queria saber o que tinha acontecido no terraço.
    - Não aconteceu nada demais! (respondi a pergunta que ele fazia em mente) - Então o que foi aquilo que vi? - (muito envergonhado) Não me lembre, por favor. Foi só um acidente. - Acidente? Não minta pra mim seu falcão20! (cutucando meu braço com o ombro) - Ela só foi me ajudar a levantar e acabei a puxando com muita força. Só isso! - Só isso? Pensei que estivessem trocando uns beijos lá em cima. - N-N-Não! Esqueça isso! Temos um jogo amanhã e já tenho tudo pronto para o jogo. Preciso me concentrar antes do treino. - Sim, senhor capitão! (batendo continência)  - Se troque logo!
    Nosso último jogo-treino estava andando muito bem, todas as mudanças que pedi estavam sendo executadas com muita destreza pelo time. Nosso ritmo estava bem equilibrado, pois era importante não cansar no jogo antes do amistoso.
    20Nota linguística: Genji faz uma referência ao apelido dele, “Taka” significa “falcão”.

    Capítulo: Capítulo 6 – Transforme os receios em coragem 57
    As trocas de passe entre Genji e eu estavam bem sincronizadas e a força do chute dele tinha aumentado. Nossa defesa ficou mais rápida e mais sólida e nosso meio-decampo mais bem arrumado, ou seja, nosso time estava preparado para o jogo de amanhã.  Mas tínhamos um problema fora de campo. Nosso time não dispunha de assistentes fora de campo, o que era importante para nós. As alunas que antes estavam nessas funções duas eram do terceiro ano e saíram por causa das provas de vestibular e uma que estava no primeiro ano foi transferida. Não ter essas assistentes significa trabalho a mais para nós que estamos jogando, isto é, gastaríamos mais energia e tempo fazendo outros trabalhos. Eu como presidente do clube, precisava resolver esse problema. A opinião do treinador era importante para a decisão final. Então fui conversar com ele durante o intervalo.
    - Natsu sensei precisamos resolver esse problema da falta de assistentes. Estamos com trabalho dobrado por causa disso. - É verdade Takeyama, estava pensando nisso e conversei com alguns professores e um deles me passou uma lista com o nome de alguns alunos do primeiro ano que não entraram em outros clubes. Tome a lista (mexendo na mochila) - (pegando a lista) O número é mediano, mas deve dar. São... (contando) doze garotas e quinze garotos. Vou focar nas garotas, elas são mais gentis na hora de tratar de alguém, mas precisamos de homens pra carregar alguns materiais. Mas o problema é que precisamos disso pra amanhã e será impossível arranjar tudo hoje. Vou pensar em uma alternativa temporária. - Deixo em suas mãos Takeyama, agora volte para o treino. Vamos diminuir o ritmo e treinar os passes e aproveitar as aberturas. - Certo. Se eu conseguir arrumar a equipe lhe mando um SMS. - Pode deixar.
    Voltei ao treino, mas com a mente nesse problema. Conseguiria eu arranjar uma equipe de auxiliares? Precisava pensar em algo rápido. Enquanto isso nosso treino estava quase no fim, então aproveitamos para treinar passes e cruzamentos. Durante os passes vi três garotas se aproximando, Inaho e suas duas amigas. Na mesma hora me veio uma lâmpada na cabeça e gritei:
    - Serão elas!
    Na lateral da grande área Maburo fez o cruzamento para mim, porém eu estava desatento por causa da ideia que tive. O que posso dizer de um jogador com um cruzamento preciso? Ele acertou em cheio minha cabeça e fui direto ao chão e só escutei meus companheiros se desesperando.

    Capítulo: Capítulo 6 – Transforme os receios em coragem 58
    Poucos minutos depois vi uma „multidão‟ de pessoas ao meu redor me fazendo várias perguntas sobre meu estado, quantos dedos eu enxergava e coisas parecidas, mas uma voz me chamou atenção. Era Inaho perguntando por mim. Fiquei um pouco surpreso pela reação dela, seu rosto demonstrava preocupação comigo.
    - Estou bem. Um pouco tonto, mas nada demais. - Sinto muito capitão, essa não era minha intenção. (Maburo se curva pedindo perdão) - Isso acontece e na verdade foi desatenção minha. Peço desculpas a todos pelo susto. - Esse é nosso capitão! Forte como um touro. Vamos levante. (Genji estende a mão para mim) - Obrigado Genji. (seguro sua mão e me levanto) - Só não tente me beijar. (diz ao meu ouvido com cara de malícia) - COMO É?! (envergonhado) - Nada capitão, nada! Vamos desmanchar o circo pessoal, o capitão está bem.
    Enquanto Genji desfazia a multidão eu me ajeitava e procurava algumas palavras para pedir o favor às meninas.
    - Meninas eu preciso falar com vocês, podem me esperar no portão da escola? Vou tomar um banho e já sigo pra lá. - É sobre o quê? (Asuna pergunta) - Um favor enorme. - Tudo bem, iremos te esperar.
    Dez minutos depois elas estavam no portão da escola como combinado. Eu precisava muito que elas dissessem sim para mim, caso contrário nós estaríamos perdidos. Kaito: - Que bom que estão aqui. Inaho: - Qual o favor? (desconfiada) Kaito: - O que vocês vão fazer amanhã de manhã? Keiko: - Não tenho nada em mente. Asuna: - Eu ia sair com meu namorado, mas a família dele vai viajar amanhã. Inaho: - E eu virei assistir o jogo de vocês amanhã com meu irmão. (olha pra mim com aquela cara de “você sabe o que vou fazer amanhã”). Asuna: - O quê? Você virá assistir o jogo? Inaho: - Sim, o meu irmão gosta de futebol. Então achei que seria uma boa ideia trazê-lo. E ele também gosta do Kaito. Asuna: - Huuuuummm...

    Capítulo: Capítulo 6 – Transforme os receios em coragem 59
    Kaito: - Que ótimo que vocês não têm não tem nada pra fazer amanhã e que você estará aqui. Keiko: - Por quê? Kaito: - Eu imploro: Sejam as assistentes do time só por amanhã! Inaho: - O quê? Asuna: - Como assim? Kaito: - As ex-integrantes saíram esse ano e estamos sem ninguém para nos dar suporte e com o jogo de amanhã teremos trabalho em dobro sem auxiliares. Asuna: - E por que nós? Kaito: - Vocês foram as primeiras pessoas em que pensei. Asuna: - Não entendi. Kaito: - O importante é saber se vocês podem me ajudar. Keiko: - Por mim tudo bem. Kaito: - Será só por amanhã, por favor. Asuna: - Huuum, só se a Inaho aceitar. Inaho: - Por quê? Asuna: - Por que aí ficaremos juntas. Inaho: - Só por isso? Asuna: - Claro! Somos amigas Inaho: - Huuuum... Se não me atrapalhar amanhã. Keiko e Asuna: - Aêêê! Kaito: - Muito obrigado garotas, o clube todo agradece a disposição de vocês. Inaho: - E o que precisamos fazer? Kaito: - É simples. Durante o intervalo vocês vão distribuir água e bebida energética para os jogadores e dar qualquer tipo de suporte durante alguma parada. Keiko: - Podemos trazer limão e mel (um “petisco” energético para atletas) para vocês. O que acha? Kaito: - Ótimo. Keiko: - Vamos nos reunir na sua casa hoje Inaho-chan? Assim podemos organizar melhor os preparativos. Inaho: - Por que em minha casa? Keiko: - Lá é nosso ponto de encontro. (sorri) Inaho: - Tudo bem. (cruza os braços insatisfeita) Asuna: - Então vou aproveitar que vou comprar algumas coisas pra mamãe e pego mais algumas coisas pra amanhã. Vamos Keiko? Keiko: - Mas e Inaho-chan?

    Capítulo: Capítulo 6 – Transforme os receios em coragem 60
    Asuna: - Eu acho que ela tem que acertar mais alguns detalhes com Takeyama-kun e também arrumar o quarto dela que deve estar uma bagunça. Inaho: - Ei não fale isso na frente dele! (brava) Asuna: - (risos) Não se preocupe, ele é um garoto sério. (olha pra mim) Kaito: - (rindo com o rosto virado) Inaho: - Fica quieto! (soca meu ombro) Kaito: - Ei me desculpe, eu só não aguentei.  Inaho: - Vão logo e estejam lá as 19:00. Entenderam? E já vão preparadas pra dormir lá. Keiko e Asuna: - Sim, senhora! Inaho: - Vamos? (olha pra mim) Kaito: - Sim.
    Nos despedimos e seguimos em rumos diferentes. A caminho de casa não trocamos muitas palavras, talvez pelo ocorrido de mais cedo. Eu tentei quebrar o silêncio algumas vezes, mas ela aparentava não querer conversar. Minha paciência começou a se esgotar com aquela cota de silêncio e então explodi.
    - AAAAHH! FALE ALGUMA COISA, CONVERSE, BRIGUE COMIGO, MAS FALE! (coloco as mãos na cabeça e grito) - (espantada) O que foi? - Você fica aí calada e com essa cara emburrada. Por favor, converse! - Que estranho você falando dessa forma, não parece você. - Eu sei que é estranho, mas é por causa do mal entendido dessa tarde. - Aquilo? Por mais que tenha sido constrangedor eu sei que foi um acidente. - Então estamos entendidos? - Sim Kaito. (sorri pra mim) - (Eu estou muito apaixonado por ela)Ótimo. Muito obrigado pela ajuda. - Eu estava lhe devendo um favor. Que hora precisamos estar lá? - O jogo é as 9:00, mas vou 7:30 com o time. Seria interessante se vocês estivessem lá ás 8:00. Pode ser? - Sim. Se precisar que eu leve mais alguma coisa é só me lig... Você não tem meu número né? - Não tenho. (seria isso uma OPORTUNIDADE?) - Liga o Bluetooth21. - Um momento. (esse é um dos dias mais felizes da minha vida) Pode passar. - Pronto. Agora me passe o seu. - (celular vibra) Recebi, vou passar o meu agora.
    21Nota de (des) informação: Como eu não conheço a sequência numérica das operadoras japonesas eu preferi deixar assim. E é possível passar o seu número via Bluetooth.

    Capítulo: Capítulo 6 – Transforme os receios em coragem 61
    - Isso não é pretexto pra ficar me ligando a qualquer hora, entendeu? - Nem pensei nisso, fique tranquila. (droga) - E como está o seu braço? - Melhorando, troco as faixas todos os dias. - E não vai atrapalhar no jogo de amanhã? - Vou tomar cuidado.
    Enquanto conversávamos o tempo passava e acabamos não prestando atenção no lugar em que estávamos. Mas em um momento uma figura conhecida me chamou atenção. Parei e olhei para o lado focando minha visão naquela forma. Aquela cerejeira florida e bem vistosa chamava minha atenção. Aquele lugar acabou se tornando especial para mim depois de todos os acontecimentos. Inaho percebeu que eu tinha parado de caminhar e virou-se para ver o que tinha acontecido. Era uma cena simples: um jovem adolescente olhando para uma sakura ao entardecer de mais um dia.
    - Aconteceu alguma coisa? - Não, nada. Só estava pensando em como essa semana foi movimentada. - (risos) Verdade. Acho que nunca teremos uma semana como essa. - Pensando bem a nossa primavera só está começando agora. - O que você quis dizer com isso? Acha que vai acontecer mais alguma coisa? - Não sei. (sorrindo) - Então só nos resta esperar. - Vamos. - Oi? (desatenta olhando a sakura) Sim, vamos.
    Em casa eu me preparava mentalmente para o jogo de amanhã. Jogar contra a Seiho sempre foi um desafio. Afinal, eles sempre estavam entre os melhores há alguns anos atrás. E nosso time começou a ganhar espaço há três anos, mas só conseguimos o campeonato ano passado e logo em cima da Seiho, ou seja, eles tinham contas a acertar conosco. Por mais que fosse um amistoso seria um jogo duro para ambos os lados. Durante minha concentração meu telefone tocou. Podia ser a Inaho!
    - Alô! (eufórico) - Calma garotão, sou eu, Genji. - O que você quer? (insatisfeito) - Estava esperando outra pessoa? Uma garota por acaso? - Não é da sua conta. - (risos) Tudo bem. Eu liguei só pra saber se posso dormir na sua casa hoje. - Por quê?

    Capítulo: Capítulo 6 – Transforme os receios em coragem 62
    - Não sei se meu despertador vai me acordar. (voz tímida) - Seus pais brigaram de novo? - Sim. - Tudo bem, pode vir. Vou esperar você no parque. - Beleza. Como sempre você me salvando. Muito obrigada Taka.  - Amigos são pra isso. Tchau. - Até. *desliga*
    Coloquei um casaco e desci para encontrar com Genji. Pai lia o jornal quando passei por ele.
    - Oi pai. - O que foi filho? - Os pais do Genji brigaram de novo e ele me perguntou se podia dormir aqui. Tem algum problema? - O que é isso filho? É claro que pode. Você vai encontrá-lo? - Sim. Vou ao parque. - Eu vou falar com sua mãe. - Obrigado pai.
    Coloquei meus tênis e fui ao encontro do meu amigo. Vinte minutos se passaram e lá estava ele. O seu pai era alcoólatra e sempre brigava com sua mãe, mas felizmente nunca passou disso. Isso abalava muito o psicológico de Genji. Afinal, filho nenhum quer ver seus pais brigando. Quando nos encontramos o saudei.
    - Yô! - E aí? - Qual foi o problema dessa vez? - O problema de sempre, bebida. Eles já tinham acabado de brigar, mas o clima lá em casa estava horrível, por isso te liguei. - Pena que esse é um problema que outra pessoa não possa resolver. - Pois é. (triste) - Vamos? Aqui fora Tá frio. - Por que Taka? Por quê? (voz de choro) Eles não prometeram viver felizes nos votos de casamento? Então por que brigam feito cão e gato? Eu só queria que eles parassem com isso e se tornassem um casal normal. (cai em prantos) - Pode chorar cara, não tem ninguém aqui. Eu sei que você deve estar segurando isso há muito tempo.

    Capítulo: Capítulo 6 – Transforme os receios em coragem 63
    Sempre que os pais dele brigavam, ele sempre me ligava perguntando se podia dormir lá em casa. Quando nos conhecemos no ano passado estávamos nos testes para entrada no time de futebol e foi a partir daquele momento em que ficamos amigos. Mas nesse um ano de amizade nunca o vi chorar por nada. Então eu só posso dizer que ele estava segurando aquela angústia há muito tempo e que uma hora aquele sentimento ruim iria explodir de dentro dele. Minha reação foi abraçá-lo para demonstrar que estava ao lado dele e que queria ajudá-lo. Ele se acalmou um pouco e secou suas lágrimas e me ameaçou caso contasse isso para alguém. Era um bom sinal de que seu estado emocional estava normalizando. Enquanto caminhávamos para casa meu telefone tocou, pensei que fosse meu pai perguntando sobre meu paradeiro. Mas era a Inaho! - A-A-Alô? - Atendeu! Milagre! Te mandei mensagens, mas você não respondeu. Já estava dormindo? - Não, eu estou indo pra casa com Genji agora. - Vocês não podem ficar de bobeira na rua. Voltem já pra casa, mas antes passem aqui. Preciso da opinião de vocês. - Não estávamos de bobeira, mas enfim, por que temos de ir à sua casa? - Quero que provem a conserva que estamos fazendo. - Então Tá, abra a porta. - Já? - Estamos praticamente em frente a sua casa. - Espere um momento. *desliga*
    Olhei para o telefone e vi a primeira ligação da Inaho e as quinze mensagens que ela me enviou. “Kaito Tá acordado?”, “Ei me responde!” foram algumas das mensagens que ela me enviou.
    - Já estão assim? - Para de falar bestagem! Ela pediu pra passarmos na casa dela? - O quê? Pra quê? - Ela quer que provemos a conserva que elas estão preparando. - É verdade, ela é do clube de culinária. Me bateu uma fome agora. - Por favor, não vá mendigar comida na casa dos outros. - A família dela já me conhece! (sorriso despreocupado) - É mesmo, mas isso não é desculpa para...  - Oi meninos, entrem. (Inaho abre a porta para nós)
    Mais uma vez ela me surpreendeu com sua beleza. Como um avental realçava a beleza de uma garota? Viajei por um instante na aparência dela.

    Capítulo: Capítulo 6 – Transforme os receios em coragem 64
    - Ei você usa óculos! - E qual o problema nisso Sakamoto-kun? - Nenhum, eles ficam bem em você. Com licença. (invadindo) - E você? Vai ficar me olhando com essa cara de bobo? Você já me viu usando óculos. - Oi? Ah sim, já vi. (corado) - Pare de me encarar e entre logo. - Com licença.
    Pela primeira vez eu entrava em sua casa. Eu estava me sentindo um pouco desconfortável, mas aos poucos fui me acostumando com o lugar. Genji já havia melhorado, ele estava bem a vontade conversando com as meninas, entretanto eu ficava calado observando a cozinha e as pessoas ao redor. Susuki Keiko viu como eu estava calado e me chamou para a conversa.
    - Takeyama-kun? Tudo bem? - Susuki-san? - (risos) Pode me chamar de Keiko, não tem problema. - Ke-Keiko-san. - Já é um começo. (risos) Por que está tão calado? - Só estou me acostumando com o lugar. - Você é diferente! (sorri) - Quê? - Esquece. E como estão os preparativos para o jogo de amanhã? - Um pouco ansioso, mas estou confiante.
    Inaho nos chama para provar a conserva.
    - Meninos provem o limão com mel que fizemos. - Uuhu vou provar algo feito pela Tachibana-san. (comemorando) - Prove logo idiota.  - Que rude! (pega o garfo e espeta uma fatia de limão coberta com mel) - Ah, Kaito pode pegar umas sacolas que deixei ali na entrada da cozinha? - Posso sim. (pegando as sacolas) - Uuuuh que delícia! Me sinto mais revigorado! Parabéns Tachibana-san. - Obrigada. Agora você Kaito. (espeta uma fatia e me oferece) Abra a boca. - Oi? (surpreso e com as mãos ocupadas) - Rápido antes que suje o chão!

    Capítulo: Capítulo 6 – Transforme os receios em coragem 65
    O que estava acontecendo aqui? Ela mesma queria me servir! Todos olharam surpresos para a atitude dela. Fiquei sem reação naquele momento, mas ela me apressou.
    - Abra logo a boca! - (abri instintivamente) Aaaah~ - O que me diz? - (...) - Fale algo. - (mastigando e engolindo sem expressar nenhuma reação) - Pessoal o que aconteceu com ele? (se vira)
    Assim como eu, os três estavam surpresos pela forma como Inaho agiu. Ela fez tudo com muita naturalidade, como se fosse algo normal, o que pra mim não era. Com o tempo ela acabou notando o que tinha feito e ficou envergonhada.
    - Me desculpe Kaito, acabei não percebendo o que fiz. - T-Tudo bem, não tem problema. E o limão está uma delícia. (recuperado)
    Depois daquele episódio conversamos mais um pouco e depois Genji e eu fomos embora para descansar. No caminho para casa nós já estávamos muito mais a vontade depois dos episódios anteriores.
    - Acho que amanhã teremos um bom jogo. - Por que Taka? - Aliviamos um pouco a tensão e acho que isso vai nos ajudar amanhã. - Concordo contigo, agora vamos logo que estou morrendo de sono. - Beleza. *telefone toca* Alô, Inaho? - Não. Sou eu, Keiko. Inaho está ocupada agora, mas me pediu para te ligar com o celular dela. - Aconteceu alguma coisa? - Sim. Ela quer que vocês liguem para todos os garotos do time e os avise que o café da manhã será na escola. Ok? - Pode deixar. - Tchau tchau.*desliga* - Tchau. - O que foi Taka? - As meninas são incríveis. - Por quê? - Elas vão preparar nosso café da manhã na escola. - Sério?

    Capítulo: Capítulo 6 – Transforme os receios em coragem 66
    - E temos que avisar pro time. Vamos logo pra casa e vamos ligar pro pessoal. - Eita! Vamos logo.
    Depois de meia hora no telefone conseguimos avisar a todos os integrantes do time, inclusive Natsu-sensei. Depois de tantas ligações estávamos muito cansados e nem percebemos a hora que caímos no sono. No dia seguinte acordamos cedo e nos preparamos para a saída. Ao chegar na escola todos do time estavam lá, exceto o Ichigo, mas já era de se esperar. Enquanto conversávamos as três garotas se aproximavam. Inaho chamou nossa atenção e pediu que a seguíssemos. Todos os garotos ficaram mais animados ao ver nossas belas auxiliares usando aventais e nos guiando até o nosso café da manhã. Ás 7:40 da manhã, estávamos na entrada do refeitório da escola. Por serem do clube de culinária as garotas tinham acesso a cozinha, mas não aos ingredientes. Mas isso não era um empecilho. Afinal, todos ficaram com os queixos ao chão com as mesas que elas arrumaram para todos os vinte e um membros. Um café da manhã incrível, não em tamanho, mas em qualidade. Salada de frutas, pães, sucos. Elas prepararam um lanche simples, porém completo para jogadores. Após comermos, formamos uma fila e agradecemos as nossas três auxiliares interinas pelo esforço. Quase saindo do refeitório vi uma figurinha que me animou. Murao veio ver o jogo e estava na porta esperando pela sua irmã.
    - Bom dia campeão! - Aniki! Bom dia! Vim ver seu jogo. - Estou vendo, e estou feliz por ter vindo. Procura pela sua irmã? - Sim, ela falou que vinha mais cedo e que perto das 9 horas eu tinha que estar aqui.  - Está feliz por ela ter te chamado? - Muito! Pela primeira vez a nee-san me chamou pra sair com ela. - Então aproveite muito esse dia, entendeu? Agora tchau! - pode deixar aniki. Bom jogo!
    Ás 8:30 os jogadores da Seiho chegaram a nossa escola. Todos aparentavam estar bem sérios com o amistoso. Já em campo nosso aquecimento estava completo e nossas mentes preparadas. Vinte minutos depois ambos os times se encontraram em campo. Cada olhar que um jogador trocava com o outro deixavam clara a rivalidade, era quase como se saíssem faíscas dos olhos.  Nos alinhamos para os cumprimentos e nos curvamos em sinal de respeito, mas a dor do vice campeonato deles estava bem vívida em seus olhares. O jogo não seria fácil.

    Capítulo: Capítulo 7 – Exploda! 67
    Nosso time sairia com a bola então Genji e eu nos posicionamos no meio do campo. A tensão era enorme e todos sentiam isso. E logo o momento mais temido aconteceu: O juiz apita o início do jogo. Toquei a bola para Genji e demos o início a essa batalha. </h5>

</div>
<?php $back="Cap #5"; $next="Cap #7"; $backs="?cap=5"; $nexts="?cap=7"?>